/* ============================================================
   HOLOS — i18n engine + dictionary
   Translates by normalized source text on text nodes, so inline
   markup (<br>, <em>, italic spans, arrows) is preserved.
   RTL flip for Hebrew + Arabic. Persisted to localStorage.
   ============================================================ */
(function () {
  'use strict';

  var RTL = { he: 1, ar: 1 };

  /* ---- dictionary: English source -> per-language translation ---- */
  var T = {
    /* NAV */
    "Methodology": { he:"שיטה", ar:"المنهجية", ru:"Методология", es:"Metodología", fr:"Méthode", de:"Methodik" },
    "Traditions": { he:"מסורות", ar:"التقاليد", ru:"Традиции", es:"Tradiciones", fr:"Traditions", de:"Traditionen" },
    "Platform": { he:"פלטפורמה", ar:"المنصة", ru:"Платформа", es:"Plataforma", fr:"Plateforme", de:"Plattform" },
    "Science": { he:"מדע", ar:"العلم", ru:"Наука", es:"Ciencia", fr:"Science", de:"Wissenschaft" },
    "Pricing": { he:"מחירים", ar:"الأسعار", ru:"Тарифы", es:"Precios", fr:"Tarifs", de:"Preise" },
    "Start free": { he:"להתחיל בחינם", ar:"ابدأ مجانًا", ru:"Начать бесплатно", es:"Empezar gratis", fr:"Commencer", de:"Kostenlos starten" },

    /* HERO */
    "Integrative Wellness Intelligence": { he:"בינת בריאות אינטגרטיבית", ar:"ذكاء العافية التكاملي", ru:"Интегративный интеллект благополучия", es:"Inteligencia de bienestar integrativa", fr:"Intelligence de bien-être intégrative", de:"Integrative Wellness-Intelligenz" },
    "The whole of you,": { he:"כל כולך,", ar:"كلّك أنت،", ru:"Вы целиком —", es:"Tu ser completo,", fr:"Vous tout entier,", de:"Sie als Ganzes," },
    "finally seen.": { he:"סוף סוף נראה.", ar:"يُرى أخيرًا.", ru:"наконец увидены.", es:"por fin visto.", fr:"enfin vu.", de:"endlich gesehen." },
    "Holos unites modern science with six of humanity's great wisdom traditions into one adaptive intelligence — so your wellness reflects body, energy, mind, and meaning. Not just your steps.": { he:"הולוס מאחד מדע מודרני עם שש ממסורות החוכמה הגדולות של האנושות לכדי בינה מסתגלת אחת — כך שהבריאות שלך משקפת גוף, אנרגיה, נפש ומשמעות. לא רק את הצעדים שלך.", ar:"يوحّد هولوس العلم الحديث مع ستٍّ من أعظم تقاليد الحكمة الإنسانية في ذكاءٍ متكيّفٍ واحد — لتعكس عافيتك الجسد والطاقة والعقل والمعنى. لا خطواتك فحسب.", ru:"Holos объединяет современную науку с шестью великими традициями мудрости человечества в единый адаптивный интеллект — чтобы ваше благополучие отражало тело, энергию, разум и смысл. А не только шаги.", es:"Holos une la ciencia moderna con seis de las grandes tradiciones de sabiduría de la humanidad en una inteligencia adaptativa, para que tu bienestar refleje cuerpo, energía, mente y sentido. No solo tus pasos.", fr:"Holos unit la science moderne à six des grandes traditions de sagesse de l'humanité en une intelligence adaptative — pour que votre bien-être reflète le corps, l'énergie, l'esprit et le sens. Pas seulement vos pas.", de:"Holos vereint moderne Wissenschaft mit sechs der großen Weisheitstraditionen der Menschheit zu einer adaptiven Intelligenz — damit Ihr Wohlbefinden Körper, Energie, Geist und Sinn widerspiegelt. Nicht nur Ihre Schritte." },
    "Take the assessment": { he:"לבצע את ההערכה", ar:"ابدأ التقييم", ru:"Пройти оценку", es:"Hacer la evaluación", fr:"Faire le bilan", de:"Zur Analyse" },
    "See the platform": { he:"לראות את הפלטפורמה", ar:"شاهد المنصة", ru:"Смотреть платформу", es:"Ver la plataforma", fr:"Voir la plateforme", de:"Plattform ansehen" },
    "Wisdom traditions": { he:"מסורות חוכמה", ar:"تقاليد الحكمة", ru:"Традиции мудрости", es:"Tradiciones de sabiduría", fr:"Traditions de sagesse", de:"Weisheitstraditionen" },
    "Balance dimensions": { he:"מימדי איזון", ar:"أبعاد التوازن", ru:"Измерений баланса", es:"Dimensiones de equilibrio", fr:"Dimensions d'équilibre", de:"Balance-Dimensionen" },
    "On the waitlist": { he:"ברשימת ההמתנה", ar:"على قائمة الانتظار", ru:"В списке ожидания", es:"En lista de espera", fr:"Sur liste d'attente", de:"Auf der Warteliste" },
    "Grounded in peer-reviewed science": { he:"מבוסס על מדע שעבר ביקורת עמיתים", ar:"مبني على علمٍ محكَّم", ru:"Основано на рецензируемой науке", es:"Basado en ciencia revisada por pares", fr:"Fondé sur une science évaluée par les pairs", de:"Auf begutachteter Wissenschaft basierend" },
    "Integral Balance": { he:"איזון אינטגרלי", ar:"التوازن التكاملي", ru:"Интегральный баланс", es:"Equilibrio integral", fr:"Équilibre intégral", de:"Integrale Balance" },
    "Swarga Mode": { he:"מצב סווארגה", ar:"وضع سوارغا", ru:"Режим Swarga", es:"Modo Swarga", fr:"Mode Swarga", de:"Swarga-Modus" },
    "Recovery": { he:"התאוששות", ar:"التعافي", ru:"Восстановление", es:"Recuperación", fr:"Récupération", de:"Erholung" },
    "Sleep": { he:"שינה", ar:"النوم", ru:"Сон", es:"Sueño", fr:"Sommeil", de:"Schlaf" },
    "Nutrition": { he:"תזונה", ar:"التغذية", ru:"Питание", es:"Nutrición", fr:"Nutrition", de:"Ernährung" },
    "Today": { he:"היום", ar:"اليوم", ru:"Сегодня", es:"Hoy", fr:"Aujourd'hui", de:"Heute" },
    "Morning ritual,": { he:"טקס בוקר,", ar:"طقس صباحي،", ru:"Утренний ритуал,", es:"Ritual matutino,", fr:"Rituel du matin,", de:"Morgenritual," },
    "tuned to Vata.": { he:"מכוון לוואטה.", ar:"مضبوط على فاتا.", ru:"настроен на Вату.", es:"ajustado a Vata.", fr:"réglé sur Vata.", de:"auf Vata abgestimmt." },
    "Warm water · 6 min breath": { he:"מים חמים · 6 דק׳ נשימה", ar:"ماء دافئ · 6 د تنفّس", ru:"Тёплая вода · 6 мин дыхания", es:"Agua tibia · 6 min respiración", fr:"Eau tiède · 6 min respiration", de:"Warmes Wasser · 6 Min Atem" },

    /* PROBLEM */
    "The problem": { he:"הבעיה", ar:"المشكلة", ru:"Проблема", es:"El problema", fr:"Le problème", de:"Das Problem" },
    "Wellness got measured.": { he:"הבריאות נמדדה.", ar:"تمّ قياس العافية.", ru:"Здоровье научились измерять.", es:"El bienestar se midió.", fr:"Le bien-être a été mesuré.", de:"Wohlbefinden wurde gemessen." },
    "It never got": { he:"היא מעולם לא", ar:"لكنّها لم", ru:"Но так и не", es:"Nunca llegó a", fr:"Il n'a jamais été", de:"Es wurde nie" },
    "understood.": { he:"הובנה.", ar:"تُفهم قط.", ru:"понятым.", es:"comprenderse.", fr:"compris.", de:"verstanden." },
    "Rings and scores tell you": { he:"טבעות וציונים אומרים לך", ar:"الحلقات والنقاط تخبرك", ru:"Кольца и баллы говорят, что", es:"Los anillos y las puntuaciones te dicen", fr:"Les anneaux et les scores vous disent", de:"Ringe und Werte sagen Ihnen," },
    "what": { he:"מה", ar:"ماذا", ru:"именно", es:"qué", fr:"ce qui", de:"was" },
    "happened. They rarely tell you why — or what to do as a whole person living a whole life.": { he:"קרה. הם לעיתים רחוקות אומרים לך למה — או מה לעשות כאדם שלם החי חיים שלמים.", ar:"حدث. ونادرًا ما تخبرك لماذا — أو ماذا تفعل كإنسانٍ كاملٍ يعيش حياةً كاملة.", ru:"произошло. И редко — почему, и что делать как целостному человеку, живущему целостной жизнью.", es:"pasó. Rara vez te dicen por qué, ni qué hacer como persona entera que vive una vida entera.", fr:"s'est passé. Rarement pourquoi — ni quoi faire en tant que personne entière vivant une vie entière.", de:"geschah. Selten warum — oder was als ganzer Mensch in einem ganzen Leben zu tun ist." },
    "Fragmented by design": { he:"מפוצל מעצם הבנייה", ar:"مجزّأ بالتصميم", ru:"Раздроблено по своей сути", es:"Fragmentado de origen", fr:"Fragmenté par nature", de:"Von Grund auf fragmentiert" },
    "Sleep in one app, food in another, stress nowhere. No single view sees the person.": { he:"שינה באפליקציה אחת, אוכל באחרת, מתח בשום מקום. אין מבט אחד שרואה את האדם.", ar:"النوم في تطبيق، والطعام في آخر، والتوتر في لا مكان. لا نظرة واحدة ترى الإنسان.", ru:"Сон в одном приложении, еда в другом, стресс — нигде. Ни один экран не видит человека целиком.", es:"El sueño en una app, la comida en otra, el estrés en ninguna. Ninguna vista ve a la persona.", fr:"Le sommeil dans une app, l'alimentation dans une autre, le stress nulle part. Aucune vue ne voit la personne.", de:"Schlaf in einer App, Essen in einer anderen, Stress nirgends. Keine Ansicht sieht den Menschen." },
    "Data without wisdom": { he:"נתונים ללא חוכמה", ar:"بيانات بلا حكمة", ru:"Данные без мудрости", es:"Datos sin sabiduría", fr:"Des données sans sagesse", de:"Daten ohne Weisheit" },
    "Modern tracking is brilliant at measurement and blind to meaning, rhythm, and purpose.": { he:"מעקב מודרני מצוין במדידה ועיוור למשמעות, למקצב ולתכלית.", ar:"التتبّع الحديث بارعٌ في القياس وأعمى عن المعنى والإيقاع والغاية.", ru:"Современный трекинг блестяще измеряет, но слеп к смыслу, ритму и цели.", es:"El seguimiento moderno mide de maravilla, pero es ciego al sentido, el ritmo y el propósito.", fr:"Le suivi moderne mesure à merveille mais ignore le sens, le rythme et le but.", de:"Modernes Tracking misst brillant, ist aber blind für Sinn, Rhythmus und Zweck." },
    "One-size protocols": { he:"פרוטוקולים אחידים", ar:"بروتوكولات موحّدة", ru:"Универсальные протоколы", es:"Protocolos únicos", fr:"Protocoles uniformes", de:"Einheitsprotokolle" },
    "Generic advice ignores constitution, season, and life stage — the things every tradition knew mattered.": { he:"עצה גנרית מתעלמת ממבנה הגוף, מהעונה ומשלב החיים — הדברים שכל מסורת ידעה שחשובים.", ar:"النصيحة العامة تتجاهل التكوين والموسم ومرحلة الحياة — أمورٌ عرف كل تقليد أهميتها.", ru:"Шаблонные советы игнорируют конституцию, сезон и этап жизни — то, что важно для каждой традиции.", es:"Los consejos genéricos ignoran la constitución, la estación y la etapa de vida, lo que toda tradición sabía que importaba.", fr:"Les conseils génériques ignorent la constitution, la saison et l'étape de vie — ce que chaque tradition savait essentiel.", de:"Pauschale Ratschläge ignorieren Konstitution, Jahreszeit und Lebensphase — was jede Tradition für wichtig hielt." },
    "Burnout, not balance": { he:"שחיקה, לא איזון", ar:"احتراق، لا توازن", ru:"Выгорание вместо баланса", es:"Agotamiento, no equilibrio", fr:"Épuisement, pas équilibre", de:"Burnout statt Balance" },
    "Optimization culture turns health into another job. People want to feel whole, not score higher.": { he:"תרבות האופטימיזציה הופכת בריאות לעוד עבודה. אנשים רוצים להרגיש שלמים, לא לצבור ניקוד.", ar:"ثقافة التحسين تحوّل الصحة إلى عملٍ آخر. الناس يريدون الشعور بالاكتمال، لا رفع النقاط.", ru:"Культура оптимизации превращает здоровье в ещё одну работу. Люди хотят чувствовать целостность, а не набирать баллы.", es:"La cultura de la optimización vuelve la salud otro trabajo. La gente quiere sentirse entera, no puntuar más.", fr:"La culture de l'optimisation fait de la santé un travail de plus. Les gens veulent se sentir entiers, pas marquer plus.", de:"Optimierungskultur macht Gesundheit zur nächsten Aufgabe. Menschen wollen sich ganz fühlen, nicht höher punkten." },

    /* METHODOLOGY */
    "The methodology": { he:"השיטה", ar:"المنهجية", ru:"Методология", es:"La metodología", fr:"La méthode", de:"Die Methodik" },
    "One intelligence.": { he:"בינה אחת.", ar:"ذكاءٌ واحد.", ru:"Один интеллект.", es:"Una inteligencia.", fr:"Une intelligence.", de:"Eine Intelligenz." },
    "Many ways of knowing.": { he:"דרכי ידיעה רבות.", ar:"طرق معرفةٍ كثيرة.", ru:"Множество способов познания.", es:"Muchas formas de saber.", fr:"De nombreux savoirs.", de:"Viele Wege des Wissens." },
    "Holos reads your data through a modern evidence engine, then translates it across the traditions that have studied human flourishing for millennia. You choose the lens. The science stays constant.": { he:"הולוס קורא את הנתונים שלך דרך מנוע ראיות מודרני, ואז מתרגם אותם דרך המסורות שחקרו את שגשוג האדם במשך אלפי שנים. אתה בוחר את העדשה. המדע נשאר קבוע.", ar:"يقرأ هولوس بياناتك عبر محرّك أدلّة حديث، ثم يترجمها عبر التقاليد التي درست ازدهار الإنسان آلاف السنين. أنت تختار العدسة، ويبقى العلم ثابتًا.", ru:"Holos считывает ваши данные современным доказательным движком, а затем переводит их на языки традиций, изучавших процветание человека тысячелетиями. Линзу выбираете вы. Наука остаётся неизменной.", es:"Holos lee tus datos con un motor de evidencia moderno y los traduce a las tradiciones que han estudiado el florecimiento humano durante milenios. Tú eliges la lente. La ciencia no cambia.", fr:"Holos lit vos données via un moteur de preuves moderne, puis les traduit à travers les traditions qui étudient l'épanouissement humain depuis des millénaires. Vous choisissez la lentille. La science reste constante.", de:"Holos liest Ihre Daten mit einer modernen Evidenz-Engine und übersetzt sie durch die Traditionen, die menschliches Gedeihen seit Jahrtausenden erforschen. Sie wählen die Linse. Die Wissenschaft bleibt konstant." },
    "Measure": { he:"למדוד", ar:"القياس", ru:"Измерять", es:"Medir", fr:"Mesurer", de:"Messen" },
    "Wearables, labs, and a 10-part assessment feed one continuous signal of your whole state.": { he:"מכשירים לבישים, בדיקות מעבדה והערכה בת 10 חלקים מזינים אות רציף אחד של מצבך השלם.", ar:"الأجهزة القابلة للارتداء والتحاليل وتقييم من 10 أجزاء تغذّي إشارة مستمرة واحدة لحالتك الكاملة.", ru:"Носимые устройства, анализы и оценка из 10 частей дают один непрерывный сигнал о вашем целостном состоянии.", es:"Wearables, analíticas y una evaluación de 10 partes alimentan una señal continua de tu estado completo.", fr:"Objets connectés, analyses et un bilan en 10 parties alimentent un signal continu de votre état global.", de:"Wearables, Labore und eine 10-teilige Analyse speisen ein durchgehendes Signal Ihres Gesamtzustands." },
    "Interpret": { he:"לפרש", ar:"التفسير", ru:"Интерпретировать", es:"Interpretar", fr:"Interpréter", de:"Deuten" },
    "An evidence model scores six domains, then maps them to the framework you choose to explore.": { he:"מודל מבוסס ראיות מנקד שישה תחומים, ואז ממפה אותם למסגרת שבחרת לחקור.", ar:"نموذجٌ قائمٌ على الأدلّة يقيّم ستة مجالات ثم يربطها بالإطار الذي تختار استكشافه.", ru:"Доказательная модель оценивает шесть областей и сопоставляет их с выбранной вами системой.", es:"Un modelo de evidencia puntúa seis dominios y los conecta con el marco que elijas explorar.", fr:"Un modèle fondé sur les preuves note six domaines, puis les relie au cadre que vous choisissez d'explorer.", de:"Ein Evidenzmodell bewertet sechs Bereiche und ordnet sie dem von Ihnen gewählten Rahmen zu." },
    "Balance": { he:"איזון", ar:"التوازن", ru:"Баланс", es:"Equilibrar", fr:"Équilibrer", de:"Ausgleichen" },
    "Recommendations adapt to your constitution, your season, and the life you're actually living.": { he:"ההמלצות מסתגלות למבנה הגוף שלך, לעונה שלך ולחיים שאתה באמת חי.", ar:"تتكيّف التوصيات مع تكوينك وموسمك والحياة التي تعيشها فعلًا.", ru:"Рекомендации подстраиваются под вашу конституцию, сезон и ту жизнь, которой вы живёте.", es:"Las recomendaciones se adaptan a tu constitución, tu estación y la vida que realmente vives.", fr:"Les recommandations s'adaptent à votre constitution, votre saison et la vie que vous menez réellement.", de:"Empfehlungen passen sich Ihrer Konstitution, Ihrer Jahreszeit und Ihrem tatsächlichen Leben an." },
    "Sustain": { he:"לקיים", ar:"الاستدامة", ru:"Поддерживать", es:"Sostener", fr:"Soutenir", de:"Halten" },
    "A wise, practical AI coach turns insight into small daily rituals you'll actually keep.": { he:"מאמן AI חכם ומעשי הופך תובנה לטקסים יומיים קטנים שבאמת תתמיד בהם.", ar:"مدرّب ذكاءٍ اصطناعيٍّ حكيمٌ وعمليّ يحوّل البصيرة إلى طقوسٍ يوميةٍ صغيرة تلتزم بها فعلًا.", ru:"Мудрый и практичный ИИ-коуч превращает инсайты в маленькие ежедневные ритуалы, которые вы действительно сохраните.", es:"Un coach de IA sabio y práctico convierte la comprensión en pequeños rituales diarios que sí mantendrás.", fr:"Un coach IA sage et pratique transforme les insights en petits rituels quotidiens que vous tiendrez vraiment.", de:"Ein weiser, praktischer KI-Coach macht aus Erkenntnis kleine tägliche Rituale, die Sie wirklich beibehalten." },

    /* FRAMEWORKS */
    "Seven lenses on a single you.": { he:"שבע עדשות על אותו אדם.", ar:"سبع عدساتٍ على ذاتك الواحدة.", ru:"Семь линз на одного вас.", es:"Siete lentes sobre un mismo tú.", fr:"Sept lentilles sur un seul vous.", de:"Sieben Linsen auf das eine Ich." },
    "Switch frameworks instantly and watch the same biometrics re-read through a different inheritance of knowledge. Compare side by side — science always in the footnotes.": { he:"החלף מסגרות באופן מיידי וצפה כיצד אותם נתונים ביומטריים נקראים מחדש דרך מורשת ידע אחרת. השווה זה לצד זה — המדע תמיד בהערות השוליים.", ar:"بدّل الأطر فورًا وشاهد القياسات الحيوية نفسها تُقرأ من جديد عبر إرثٍ معرفيٍّ مختلف. قارن جنبًا إلى جنب — والعلم دائمًا في الحواشي.", ru:"Мгновенно переключайте системы и смотрите, как одни и те же биометрические данные читаются через иное наследие знания. Сравнивайте бок о бок — наука всегда в сносках.", es:"Cambia de marco al instante y observa cómo los mismos biomarcadores se releen desde otra herencia de conocimiento. Compara lado a lado, con la ciencia siempre al pie.", fr:"Changez de cadre instantanément et voyez les mêmes données biométriques relues à travers un autre héritage de savoir. Comparez côte à côte — la science toujours en note.", de:"Wechseln Sie sofort den Rahmen und sehen Sie dieselben Biomarker durch ein anderes Wissenserbe neu gelesen. Vergleichen Sie nebeneinander — die Wissenschaft stets in den Fußnoten." },
    "Swarga Integral Wellness System": { he:"מערכת הבריאות האינטגרלית סווארגה", ar:"نظام سوارغا التكاملي للعافية", ru:"Интегральная система благополучия Swarga", es:"Sistema Integral de Bienestar Swarga", fr:"Système de bien-être intégral Swarga", de:"Swarga Integrales Wellness-System" },
    "Our synthesis. Eleven dimensions span the physical, energetic, emotional, mental, relational, and existential — fused with dosha, five-element, and life-balance models into one living portrait.": { he:"הסינתזה שלנו. אחד-עשר מימדים פורשים את הפיזי, האנרגטי, הרגשי, המנטלי, היחסי והקיומי — ממוזגים עם מודלים של דושה, חמשת היסודות ואיזון החיים לכדי דיוקן חי אחד.", ar:"خلاصتنا. أحد عشر بُعدًا تمتدّ عبر الجسدي والطاقي والعاطفي والذهني والعلائقي والوجودي — مدمجةً مع نماذج الدوشا والعناصر الخمسة وتوازن الحياة في صورةٍ حيّةٍ واحدة.", ru:"Наш синтез. Одиннадцать измерений охватывают физическое, энергетическое, эмоциональное, ментальное, социальное и экзистенциальное — слитые с моделями доши, пяти элементов и баланса жизни в один живой портрет.", es:"Nuestra síntesis. Once dimensiones abarcan lo físico, energético, emocional, mental, relacional y existencial, fusionadas con los modelos de dosha, cinco elementos y equilibrio vital en un retrato vivo.", fr:"Notre synthèse. Onze dimensions couvrent le physique, l'énergétique, l'émotionnel, le mental, le relationnel et l'existentiel — fondues aux modèles dosha, cinq éléments et équilibre de vie en un portrait vivant.", de:"Unsere Synthese. Elf Dimensionen umfassen das Körperliche, Energetische, Emotionale, Mentale, Relationale und Existenzielle — verschmolzen mit Dosha-, Fünf-Elemente- und Lebensbalance-Modellen zu einem lebendigen Porträt." },
    "Explore Swarga mode": { he:"לחקור את מצב סווארגה", ar:"استكشف وضع سوارغا", ru:"Открыть режим Swarga", es:"Explorar modo Swarga", fr:"Explorer le mode Swarga", de:"Swarga-Modus erkunden" },
    "Evidence-Based Nutrition": { he:"תזונה מבוססת ראיות", ar:"التغذية القائمة على الأدلّة", ru:"Доказательное питание", es:"Nutrición basada en evidencia", fr:"Nutrition fondée sur les preuves", de:"Evidenzbasierte Ernährung" },
    "The scientific backbone. Five pillars distilled from metabolic, sleep, and exercise research — the constant that every other lens is reconciled against.": { he:"עמוד השדרה המדעי. חמישה עמודי תווך שזוקקו ממחקרי מטבוליזם, שינה ופעילות גופנית — הקבוע שכל עדשה אחרת מיושבת מולו.", ar:"العمود الفقري العلمي. خمس ركائز مستخلصة من أبحاث الأيض والنوم والتمرين — الثابت الذي تُعاير عليه كل عدسةٍ أخرى.", ru:"Научная основа. Пять столпов, выведенных из исследований метаболизма, сна и физической активности, — константа, с которой сверяется каждая другая линза.", es:"La columna científica. Cinco pilares destilados de la investigación metabólica, del sueño y del ejercicio: la constante con la que se concilia cada lente.", fr:"L'ossature scientifique. Cinq piliers issus de la recherche sur le métabolisme, le sommeil et l'exercice — la constante à laquelle chaque lentille est rapportée.", de:"Das wissenschaftliche Rückgrat. Fünf Säulen aus Stoffwechsel-, Schlaf- und Bewegungsforschung — die Konstante, an der jede andere Linse ausgerichtet wird." },
    "Ayurveda · The Three Doshas": { he:"איורוודה · שלוש הדושות", ar:"الأيورفيدا · الدوشات الثلاث", ru:"Аюрведа · Три доши", es:"Ayurveda · Las tres doshas", fr:"Ayurveda · Les trois doshas", de:"Ayurveda · Die drei Doshas" },
    "Your constitution read as Vata, Pitta, and Kapha — air, fire, and earth. Holos surfaces your dominant dosha and tunes routine, food, and rhythm to rebalance it through the seasons.": { he:"מבנה הגוף שלך נקרא כוואטה, פיטה וקאפה — אוויר, אש ואדמה. הולוס חושף את הדושה הדומיננטית שלך ומכוון שגרה, מזון ומקצב כדי לאזן אותה מחדש לאורך העונות.", ar:"يُقرأ تكوينك كفاتا وبيتا وكافا — هواء ونار وأرض. يكشف هولوس دوشاك الغالبة ويضبط الروتين والطعام والإيقاع لإعادة توازنها عبر الفصول.", ru:"Ваша конституция читается как Вата, Питта и Капха — воздух, огонь и земля. Holos выявляет доминирующую дошу и настраивает режим, питание и ритм, чтобы восстановить баланс по сезонам.", es:"Tu constitución leída como Vata, Pitta y Kapha: aire, fuego y tierra. Holos revela tu dosha dominante y ajusta rutina, comida y ritmo para reequilibrarla con las estaciones.", fr:"Votre constitution lue comme Vata, Pitta et Kapha — air, feu et terre. Holos révèle votre dosha dominant et règle routine, alimentation et rythme pour le rééquilibrer au fil des saisons.", de:"Ihre Konstitution gelesen als Vata, Pitta und Kapha — Luft, Feuer und Erde. Holos zeigt Ihr dominantes Dosha und stimmt Routine, Ernährung und Rhythmus auf den Ausgleich über die Jahreszeiten ab." },
    "Daoist Wellness · Five Elements": { he:"בריאות דאואיסטית · חמשת היסודות", ar:"عافية طاوية · العناصر الخمسة", ru:"Даосское благополучие · Пять элементов", es:"Bienestar daoísta · Cinco elementos", fr:"Bien-être taoïste · Cinq éléments", de:"Daoistisches Wohlbefinden · Fünf Elemente" },
    "Balance as flow. Holos maps your state across Wood, Fire, Earth, Metal, and Water, reads your Yin–Yang tilt, and adapts guidance to the turning of the season.": { he:"איזון כזרימה. הולוס ממפה את מצבך על פני עץ, אש, אדמה, מתכת ומים, קורא את נטיית היין-יאנג שלך, ומתאים הנחיה למפנה העונה.", ar:"التوازن كتدفّق. يرسم هولوس حالتك عبر الخشب والنار والأرض والمعدن والماء، ويقرأ ميل اليين واليانغ لديك، ويكيّف الإرشاد مع تبدّل الفصل.", ru:"Баланс как поток. Holos отображает ваше состояние через Дерево, Огонь, Землю, Металл и Воду, считывает наклон Инь–Ян и подстраивает рекомендации под смену сезона.", es:"Equilibrio como flujo. Holos mapea tu estado entre Madera, Fuego, Tierra, Metal y Agua, lee tu balance Yin–Yang y adapta la guía al giro de la estación.", fr:"L'équilibre comme flux. Holos cartographie votre état entre Bois, Feu, Terre, Métal et Eau, lit votre inclinaison Yin–Yang et adapte les conseils au tournant de la saison.", de:"Balance als Fluss. Holos verortet Ihren Zustand zwischen Holz, Feuer, Erde, Metall und Wasser, liest Ihre Yin–Yang-Neigung und passt die Führung an den Wechsel der Jahreszeit an." },
    "Rambam · The Art of Moderation": { he:"רמב\"ם · אמנות המתינות", ar:"الرمبام · فنّ الاعتدال", ru:"Рамбам · Искусство умеренности", es:"Rambam · El arte de la moderación", fr:"Rambam · L'art de la modération", de:"Rambam · Die Kunst der Mäßigung" },
    "An educational lens drawn from Maimonides' medical writings: moderation, sound digestion, daily movement, and the prevention of illness before it begins — the mind and body kept in harmony.": { he:"עדשה חינוכית הנשענת על כתביו הרפואיים של הרמב\"ם: מתינות, עיכול תקין, תנועה יומית, ומניעת מחלה בטרם תתחיל — הנפש והגוף נשמרים בהרמוניה.", ar:"عدسة تعليمية مستمدّة من كتابات ابن ميمون الطبية: الاعتدال، وحسن الهضم، والحركة اليومية، والوقاية من المرض قبل بدايته — مع إبقاء العقل والجسد في انسجام.", ru:"Образовательная линза из медицинских трудов Маймонида: умеренность, здоровое пищеварение, ежедневное движение и предотвращение болезни до её начала — разум и тело в гармонии.", es:"Una lente educativa de los escritos médicos de Maimónides: moderación, buena digestión, movimiento diario y prevenir la enfermedad antes de que empiece, con mente y cuerpo en armonía.", fr:"Une lentille éducative tirée des écrits médicaux de Maïmonide : modération, bonne digestion, mouvement quotidien et prévention de la maladie avant qu'elle ne survienne — l'esprit et le corps en harmonie.", de:"Eine erzieherische Linse aus Maimonides' medizinischen Schriften: Mäßigung, gute Verdauung, tägliche Bewegung und Vorbeugung von Krankheit, bevor sie beginnt — Geist und Körper in Harmonie." },
    "Hippocratic Approach": { he:"הגישה ההיפוקרטית", ar:"النهج الأبقراطي", ru:"Гиппократов подход", es:"Enfoque hipocrático", fr:"Approche hippocratique", de:"Hippokratischer Ansatz" },
    "\"Let food be thy medicine.\" The original preventive philosophy — balance, environment, and lifestyle as the foundations of lasting health.": { he:"\"יהי המזון לתרופתך.\" פילוסופיית המניעה המקורית — איזון, סביבה ואורח חיים כיסודות של בריאות מתמשכת.", ar:"\"ليكن غذاؤك دواءك.\" فلسفة الوقاية الأصلية — التوازن والبيئة ونمط الحياة أُسسًا لصحةٍ دائمة.", ru:"«Пусть пища станет лекарством». Изначальная философия профилактики — баланс, среда и образ жизни как основа устойчивого здоровья.", es:"«Que tu alimento sea tu medicina». La filosofía preventiva original: equilibrio, entorno y estilo de vida como bases de una salud duradera.", fr:"« Que ton aliment soit ta médecine. » La philosophie préventive originelle — équilibre, environnement et mode de vie comme fondements d'une santé durable.", de:"„Eure Nahrung sei eure Medizin.“ Die ursprüngliche Präventionsphilosophie — Balance, Umfeld und Lebensstil als Grundlagen dauerhafter Gesundheit." },
    "Avicenna · The Canon of Habit": { he:"אבן סינא · קאנון ההרגל", ar:"ابن سينا · قانون العادة", ru:"Авиценна · Канон привычки", es:"Avicena · El canon del hábito", fr:"Avicenne · Le canon de l'habitude", de:"Avicenna · Der Kanon der Gewohnheit" },
    "From The Canon of Medicine: your constitution shaped by daily habit and environment. Holos reads temperament and tunes the controllable rhythms of your day.": { he:"מתוך \"הקאנון של הרפואה\": מבנה הגוף שלך מעוצב על ידי הרגל יומי וסביבה. הולוס קורא מזג ומכוון את המקצבים הניתנים לשליטה ביומך.", ar:"من \"القانون في الطب\": تكوينك تصوغه العادة اليومية والبيئة. يقرأ هولوس المزاج ويضبط إيقاعات يومك القابلة للتحكّم.", ru:"Из «Канона врачебной науки»: вашу конституцию формируют ежедневная привычка и среда. Holos считывает темперамент и настраивает управляемые ритмы вашего дня.", es:"Del Canon de Medicina: tu constitución moldeada por el hábito diario y el entorno. Holos lee el temperamento y ajusta los ritmos controlables de tu día.", fr:"Du Canon de la médecine : votre constitution façonnée par l'habitude quotidienne et l'environnement. Holos lit le tempérament et règle les rythmes maîtrisables de votre journée.", de:"Aus dem Kanon der Medizin: Ihre Konstitution geformt von täglicher Gewohnheit und Umfeld. Holos liest das Temperament und stimmt die steuerbaren Rhythmen Ihres Tages ab." },
    "Tibetan Wellness · Three Humors": { he:"בריאות טיבטית · שלוש הליחות", ar:"العافية التبتية · الأخلاط الثلاثة", ru:"Тибетское благополучие · Три начала", es:"Bienestar tibetano · Tres humores", fr:"Bien-être tibétain · Trois humeurs", de:"Tibetisches Wohlbefinden · Drei Säfte" },
    "Presented respectfully and educationally: the balance of Wind (rLung), Bile (mKhris-pa), and Phlegm (Bad-kan) as a window into energy, metabolism, and steadiness.": { he:"מוצג בכבוד ולמטרות חינוך: האיזון של רוח (רלונג), מרה (טריפה) וליחה (בֵּקֶן) כחלון לאנרגיה, מטבוליזם ויציבות.", ar:"يُقدَّم باحترامٍ وبهدفٍ تعليمي: توازن الريح (رلونغ) والصفراء (تريبا) والبلغم (بادكان) كنافذةٍ على الطاقة والأيض والثبات.", ru:"Представлено уважительно и в образовательных целях: баланс Ветра (рлунг), Желчи (трипа) и Слизи (бекен) как окно в энергию, метаболизм и устойчивость.", es:"Presentado con respeto y fin educativo: el equilibrio de Viento (rLung), Bilis (mKhris-pa) y Flema (Bad-kan) como ventana a la energía, el metabolismo y la firmeza.", fr:"Présenté avec respect et à but éducatif : l'équilibre du Vent (rLung), de la Bile (mKhris-pa) et du Flegme (Bad-kan) comme fenêtre sur l'énergie, le métabolisme et la stabilité.", de:"Respektvoll und lehrreich dargestellt: das Gleichgewicht von Wind (rLung), Galle (mKhris-pa) und Schleim (Bad-kan) als Fenster zu Energie, Stoffwechsel und Beständigkeit." },

    /* ASSESSMENT */
    "The assessment": { he:"ההערכה", ar:"التقييم", ru:"Оценка", es:"La evaluación", fr:"Le bilan", de:"Die Analyse" },
    "Ten minutes.": { he:"עשר דקות.", ar:"عشر دقائق.", ru:"Десять минут.", es:"Diez minutos.", fr:"Dix minutes.", de:"Zehn Minuten." },
    "A whole portrait.": { he:"דיוקן שלם.", ar:"صورةٌ كاملة.", ru:"Целостный портрет.", es:"Un retrato completo.", fr:"Un portrait entier.", de:"Ein ganzes Porträt." },
    "Ten gentle sections — from nutrition and sleep to purpose and relationships — that feel less like a medical form and more like being truly asked about your life.": { he:"עשרה חלקים עדינים — מתזונה ושינה ועד תכלית ומערכות יחסים — שמרגישים פחות כמו טופס רפואי ויותר כמו שמתעניינים בך באמת.", ar:"عشرة أقسام لطيفة — من التغذية والنوم إلى الغاية والعلاقات — تبدو أقرب إلى سؤالٍ صادقٍ عن حياتك منها إلى استمارةٍ طبية.", ru:"Десять мягких разделов — от питания и сна до смысла и отношений — которые ощущаются не как медицинская анкета, а как искренний разговор о вашей жизни.", es:"Diez secciones suaves —de la nutrición y el sueño al propósito y las relaciones— que se sienten menos como un formulario médico y más como que de verdad preguntan por tu vida.", fr:"Dix sections douces — de la nutrition et du sommeil au sens et aux relations — qui ressemblent moins à un formulaire médical qu'à une vraie attention à votre vie.", de:"Zehn sanfte Abschnitte — von Ernährung und Schlaf bis Sinn und Beziehungen — die sich weniger wie ein medizinisches Formular anfühlen als wie echtes Interesse an Ihrem Leben." },
    "Section 07 / 10 · Emotional Wellbeing": { he:"חלק 07 / 10 · רווחה רגשית", ar:"القسم 07 / 10 · العافية العاطفية", ru:"Раздел 07 / 10 · Эмоциональное благополучие", es:"Sección 07 / 10 · Bienestar emocional", fr:"Section 07 / 10 · Bien-être émotionnel", de:"Abschnitt 07 / 10 · Emotionales Wohlbefinden" },
    "When the day overwhelms you, how do you most often respond?": { he:"כשהיום מציף אותך, כיצד אתה מגיב לרוב?", ar:"عندما يثقل عليك اليوم، كيف تستجيب غالبًا؟", ru:"Когда день переполняет вас, как вы чаще всего реагируете?", es:"Cuando el día te desborda, ¿cómo sueles responder?", fr:"Quand la journée vous submerge, comment réagissez-vous le plus souvent ?", de:"Wenn der Tag Sie überfordert, wie reagieren Sie meist?" },
    "I pause and breathe — I've built a way back to center": { he:"אני עוצר ונושם — בניתי דרך לחזור למרכז", ar:"أتوقّف وأتنفّس — بنيتُ طريقًا للعودة إلى مركزي", ru:"Я останавливаюсь и дышу — я нашёл путь обратно к центру", es:"Hago una pausa y respiro: he creado un camino de vuelta al centro", fr:"Je m'arrête et je respire — j'ai trouvé un retour au centre", de:"Ich halte inne und atme — ich habe einen Weg zurück zur Mitte" },
    "I push through and deal with it later": { he:"אני דוחף קדימה ומטפל בזה אחר כך", ar:"أتجاوز وأتعامل معه لاحقًا", ru:"Я продавливаю и разбираюсь позже", es:"Sigo adelante y lo afronto después", fr:"Je tiens bon et je gère plus tard", de:"Ich mache weiter und kümmere mich später" },
    "I reach out to someone I trust": { he:"אני פונה למישהו שאני סומך עליו", ar:"أتواصل مع شخصٍ أثق به", ru:"Я обращаюсь к тому, кому доверяю", es:"Acudo a alguien de confianza", fr:"Je me tourne vers une personne de confiance", de:"Ich wende mich an jemanden, dem ich vertraue" },
    "I tend to absorb it quietly and carry on": { he:"אני נוטה לספוג זאת בשקט וממשיך", ar:"أميل إلى استيعابه بهدوءٍ والمضيّ", ru:"Обычно я молча принимаю это и иду дальше", es:"Suelo asumirlo en silencio y seguir", fr:"J'ai tendance à l'absorber en silence et à continuer", de:"Ich nehme es meist still hin und mache weiter" },
    "Adaptive · your answers reshape what comes next": { he:"מסתגל · התשובות שלך מעצבות את הבא", ar:"تكيّفي · إجاباتك تعيد تشكيل ما يلي", ru:"Адаптивно · ваши ответы меняют дальнейшее", es:"Adaptativo · tus respuestas moldean lo que sigue", fr:"Adaptatif · vos réponses façonnent la suite", de:"Adaptiv · Ihre Antworten formen das Weitere" },
    "Back": { he:"חזרה", ar:"رجوع", ru:"Назад", es:"Atrás", fr:"Retour", de:"Zurück" },
    "Continue": { he:"להמשיך", ar:"متابعة", ru:"Продолжить", es:"Continuar", fr:"Continuer", de:"Weiter" },
    "Sections": { he:"חלקים", ar:"أقسام", ru:"Разделов", es:"Secciones", fr:"Sections", de:"Abschnitte" },
    "Profile · Nutrition · Sleep · Stress · Energy · Activity · Emotion · Purpose · Relationships · Balance.": { he:"פרופיל · תזונה · שינה · מתח · אנרגיה · פעילות · רגש · תכלית · יחסים · איזון.", ar:"الملف · التغذية · النوم · التوتر · الطاقة · النشاط · العاطفة · الغاية · العلاقات · التوازن.", ru:"Профиль · Питание · Сон · Стресс · Энергия · Активность · Эмоции · Смысл · Отношения · Баланс.", es:"Perfil · Nutrición · Sueño · Estrés · Energía · Actividad · Emoción · Propósito · Relaciones · Equilibrio.", fr:"Profil · Nutrition · Sommeil · Stress · Énergie · Activité · Émotion · Sens · Relations · Équilibre.", de:"Profil · Ernährung · Schlaf · Stress · Energie · Aktivität · Emotion · Sinn · Beziehungen · Balance." },
    "Adaptive": { he:"מסתגל", ar:"تكيّفي", ru:"Адаптивно", es:"Adaptativo", fr:"Adaptatif", de:"Adaptiv" },
    "No two assessments are the same — each answer branches the path the way a good practitioner would.": { he:"אין שתי הערכות זהות — כל תשובה מפצלת את המסלול כפי שמטפל טוב היה עושה.", ar:"لا يتشابه تقييمان — كل إجابةٍ تفرّع المسار كما يفعل ممارسٌ بارع.", ru:"Двух одинаковых оценок не бывает — каждый ответ ветвит путь, как сделал бы хороший специалист.", es:"No hay dos evaluaciones iguales: cada respuesta ramifica el camino como lo haría un buen profesional.", fr:"Aucun bilan ne se ressemble — chaque réponse ramifie le parcours comme le ferait un bon praticien.", de:"Keine zwei Analysen gleichen sich — jede Antwort verzweigt den Weg wie eine gute Fachperson." },
    "Living": { he:"חי", ar:"حيّ", ru:"Живое", es:"Vivo", fr:"Vivant", de:"Lebendig" },
    "Re-check in monthly. Your portrait breathes with the seasons of your life, not a one-time snapshot.": { he:"בדיקה מחדש מדי חודש. הדיוקן שלך נושם עם עונות חייך, לא תצלום חד-פעמי.", ar:"أعد التقييم شهريًا. صورتك تتنفّس مع فصول حياتك، لا لقطةً لمرّةٍ واحدة.", ru:"Перепроверяйтесь ежемесячно. Ваш портрет дышит вместе с сезонами вашей жизни, а не разовый снимок.", es:"Revísate cada mes. Tu retrato respira con las estaciones de tu vida, no es una foto única.", fr:"Refaites le point chaque mois. Votre portrait respire au rythme des saisons de votre vie, pas un cliché unique.", de:"Prüfen Sie monatlich nach. Ihr Porträt atmet mit den Jahreszeiten Ihres Lebens, keine einmalige Momentaufnahme." },

    /* PLATFORM / RESULTS */
    "The results experience": { he:"חוויית התוצאות", ar:"تجربة النتائج", ru:"Опыт результатов", es:"La experiencia de resultados", fr:"L'expérience des résultats", de:"Das Ergebnis-Erlebnis" },
    "Results that feel like": { he:"תוצאות שמרגישות כמו", ar:"نتائج تشعر وكأنّك", ru:"Результаты, в которых вы", es:"Resultados que se sienten como", fr:"Des résultats qui donnent le sentiment d'être", de:"Ergebnisse, die sich anfühlen, als" },
    "being": { he:"להיות", ar:"", ru:"", es:"", fr:"", de:"" },
    "Six scores, a living balance wheel, and visualizations drawn from every tradition — rendered with the restraint of a fine instrument, not a dashboard.": { he:"שישה ציונים, גלגל איזון חי, וויזואליזציות השאובות מכל מסורת — מעוצבות באיפוק של כלי נגינה משובח, לא לוח בקרה.", ar:"ست نقاط، وعجلة توازنٍ حيّة، وتصوّراتٌ مستمدّةٌ من كل تقليد — مصمَّمة بانضباط آلةٍ راقية، لا لوحة بيانات.", ru:"Шесть оценок, живое колесо баланса и визуализации из каждой традиции — оформленные со сдержанностью тонкого инструмента, а не приборной панели.", es:"Seis puntuaciones, una rueda de equilibrio viva y visualizaciones de cada tradición, con la sobriedad de un instrumento fino, no un panel.", fr:"Six scores, une roue d'équilibre vivante et des visualisations issues de chaque tradition — avec la retenue d'un bel instrument, pas d'un tableau de bord.", de:"Sechs Werte, ein lebendiges Balance-Rad und Visualisierungen aus jeder Tradition — mit der Zurückhaltung eines feinen Instruments, nicht eines Dashboards." },
    "Wellness": { he:"בריאות", ar:"العافية", ru:"Благополучие", es:"Bienestar", fr:"Bien-être", de:"Wohlbefinden" },
    "Energy": { he:"אנרגיה", ar:"الطاقة", ru:"Энергия", es:"Energía", fr:"Énergie", de:"Energie" },
    "Lifestyle": { he:"אורח חיים", ar:"نمط الحياة", ru:"Образ жизни", es:"Estilo de vida", fr:"Mode de vie", de:"Lebensstil" },
    "Life Balance Wheel": { he:"גלגל איזון החיים", ar:"عجلة توازن الحياة", ru:"Колесо баланса жизни", es:"Rueda del equilibrio vital", fr:"Roue d'équilibre de vie", de:"Lebensbalance-Rad" },
    "Your portrait": { he:"הדיוקן שלך", ar:"صورتك", ru:"Ваш портрет", es:"Tu retrato", fr:"Votre portrait", de:"Ihr Porträt" },
    "Seasonal target": { he:"יעד עונתי", ar:"الهدف الموسمي", ru:"Сезонная цель", es:"Objetivo estacional", fr:"Cible saisonnière", de:"Saisonales Ziel" },
    "Screenshot": { he:"צילום מסך", ar:"لقطة شاشة", ru:"Скриншот", es:"Captura", fr:"Capture", de:"Screenshot" },
    "Daily plan view": { he:"תצוגת תוכנית יומית", ar:"عرض الخطة اليومية", ru:"Дневной план", es:"Vista del plan diario", fr:"Vue du plan du jour", de:"Tagesplan-Ansicht" },
    "Tradition compare": { he:"השוואת מסורות", ar:"مقارنة التقاليد", ru:"Сравнение традиций", es:"Comparar tradiciones", fr:"Comparer les traditions", de:"Traditionsvergleich" },
    "Habit streaks": { he:"רצפי הרגלים", ar:"سلاسل العادات", ru:"Серии привычек", es:"Rachas de hábitos", fr:"Séries d'habitudes", de:"Gewohnheits-Serien" },

    /* COACH */
    "The AI coach": { he:"מאמן ה-AI", ar:"مدرّب الذكاء الاصطناعي", ru:"ИИ-коуч", es:"El coach de IA", fr:"Le coach IA", de:"Der KI-Coach" },
    "A guide that's read": { he:"מדריך שקרא", ar:"مرشدٌ قرأ", ru:"Наставник, прочитавший", es:"Un guía que ha leído", fr:"Un guide qui a lu", de:"Ein Begleiter, der" },
    "every tradition.": { he:"כל מסורת.", ar:"كل تقليد.", ru:"каждую традицию.", es:"cada tradición.", fr:"chaque tradition.", de:"jede Tradition gelesen hat." },
    "Wise, practical, supportive, and evidence-aware. It explains your results, compares what each tradition would suggest, and turns it into habits sized for your real life.": { he:"חכם, מעשי, תומך ומודע לראיות. הוא מסביר את התוצאות שלך, משווה את מה שכל מסורת תציע, והופך זאת להרגלים בגודל המתאים לחיים האמיתיים שלך.", ar:"حكيم، عملي، داعم، وواعٍ بالأدلّة. يشرح نتائجك، ويقارن ما يقترحه كل تقليد، ويحوّله إلى عاداتٍ بحجم حياتك الحقيقية.", ru:"Мудрый, практичный, поддерживающий и опирающийся на доказательства. Он объясняет ваши результаты, сравнивает, что предложила бы каждая традиция, и превращает это в привычки под вашу реальную жизнь.", es:"Sabio, práctico, cercano y con base en la evidencia. Explica tus resultados, compara lo que sugeriría cada tradición y lo convierte en hábitos a la medida de tu vida real.", fr:"Sage, pratique, bienveillant et fondé sur les preuves. Il explique vos résultats, compare ce que suggérerait chaque tradition et le transforme en habitudes à la taille de votre vraie vie.", de:"Weise, praktisch, unterstützend und evidenzbewusst. Er erklärt Ihre Ergebnisse, vergleicht, was jede Tradition empfehlen würde, und macht daraus Gewohnheiten im Maß Ihres echten Lebens." },
    "Explains results": { he:"מסביר תוצאות", ar:"يشرح النتائج", ru:"Объясняет результаты", es:"Explica resultados", fr:"Explique les résultats", de:"Erklärt Ergebnisse" },
    "Compares traditions": { he:"משווה מסורות", ar:"يقارن التقاليد", ru:"Сравнивает традиции", es:"Compara tradiciones", fr:"Compare les traditions", de:"Vergleicht Traditionen" },
    "Builds habits": { he:"בונה הרגלים", ar:"يبني العادات", ru:"Формирует привычки", es:"Crea hábitos", fr:"Crée des habitudes", de:"Baut Gewohnheiten auf" },
    "Plans your week": { he:"מתכנן את השבוע שלך", ar:"يخطّط أسبوعك", ru:"Планирует вашу неделю", es:"Planifica tu semana", fr:"Planifie votre semaine", de:"Plant Ihre Woche" },
    "My energy keeps crashing at 3pm. What do I do?": { he:"האנרגיה שלי צונחת כל יום בשלוש אחר הצהריים. מה לעשות?", ar:"طاقتي تنهار كل يوم عند الثالثة عصرًا. ماذا أفعل؟", ru:"У меня каждый день в три часа дня падает энергия. Что делать?", es:"Mi energía se desploma a las 3 de la tarde. ¿Qué hago?", fr:"Mon énergie s'effondre chaque jour à 15 h. Que faire ?", de:"Meine Energie sackt jeden Tag um 15 Uhr ab. Was tun?" },
    "Holos · integrative coach": { he:"הולוס · מאמן אינטגרטיבי", ar:"هولوس · مدرّب تكاملي", ru:"Holos · интегративный коуч", es:"Holos · coach integrativo", fr:"Holos · coach intégratif", de:"Holos · integrativer Coach" },
    "One small ritual": { he:"טקס קטן אחד", ar:"طقسٌ صغيرٌ واحد", ru:"Один маленький ритуал", es:"Un pequeño ritual", fr:"Un petit rituel", de:"Ein kleines Ritual" },

    /* FOUNDER */
    "Founder & clinical lead": { he:"מייסד ומוביל קליני", ar:"المؤسس والمسؤول السريري", ru:"Основатель и клинический руководитель", es:"Fundador y director clínico", fr:"Fondateur et responsable clinique", de:"Gründer & klinische Leitung" },
    "Founder · Integrative Nutrition & Wellness": { he:"מייסד · תזונה ובריאות אינטגרטיבית", ar:"مؤسس · التغذية والعافية التكاملية", ru:"Основатель · интегративное питание и благополучие", es:"Fundador · Nutrición y bienestar integrativos", fr:"Fondateur · Nutrition et bien-être intégratifs", de:"Gründer · Integrative Ernährung & Wellness" },
    "Years in practice": { he:"שנות פרקטיקה", ar:"سنوات الممارسة", ru:"Лет практики", es:"Años de práctica", fr:"Ans de pratique", de:"Jahre Praxis" },
    "Traditions studied": { he:"מסורות שנחקרו", ar:"تقاليد دُرست", ru:"Изучено традиций", es:"Tradiciones estudiadas", fr:"Traditions étudiées", de:"Studierte Traditionen" },
    "Clients guided": { he:"לקוחות שהודרכו", ar:"عملاء أُرشدوا", ru:"Клиентов сопровождено", es:"Clientes guiados", fr:"Clients accompagnés", de:"Begleitete Klienten" },

    /* TESTIMONIALS */
    "Lived with it": { he:"חיו עם זה", ar:"عاشوا معه", ru:"Прожили с этим", es:"Lo vivieron", fr:"Ils l'ont vécu", de:"Damit gelebt" },
    "The first wellness app": { he:"אפליקציית הבריאות הראשונה", ar:"أول تطبيق عافية", ru:"Первое приложение здоровья,", es:"La primera app de bienestar", fr:"La première app de bien-être", de:"Die erste Wellness-App," },
    "that felt human.": { he:"שהרגישה אנושית.", ar:"يبدو إنسانيًّا.", ru:"которое ощущается человечным.", es:"que se sintió humana.", fr:"qui semblait humaine.", de:"die sich menschlich anfühlte." },

    /* SCIENCE */
    "Scientific foundation": { he:"בסיס מדעי", ar:"أساس علمي", ru:"Научная основа", es:"Fundamento científico", fr:"Fondement scientifique", de:"Wissenschaftliche Grundlage" },
    "Ancient lenses.": { he:"עדשות עתיקות.", ar:"عدساتٌ قديمة.", ru:"Древние линзы.", es:"Lentes antiguas.", fr:"Lentilles anciennes.", de:"Alte Linsen." },
    "Modern rigor.": { he:"קפדנות מודרנית.", ar:"دقّةٌ حديثة.", ru:"Современная строгость.", es:"Rigor moderno.", fr:"Rigueur moderne.", de:"Moderne Strenge." },
    "Every recommendation traces back to peer-reviewed evidence. Traditions are offered as educational frameworks for reflection — never as medical claims — and labeled as such throughout.": { he:"כל המלצה ניתנת לעקיבה לראיות שעברו ביקורת עמיתים. המסורות מוצעות כמסגרות חינוכיות להרהור — לעולם לא כטענות רפואיות — ומסומנות ככאלה לכל אורך הדרך.", ar:"كل توصية تعود إلى أدلّةٍ محكَّمة. وتُقدَّم التقاليد كأُطرٍ تعليميةٍ للتأمّل — لا كادّعاءاتٍ طبية — وتُوسم كذلك في كل مكان.", ru:"Каждая рекомендация восходит к рецензируемым доказательствам. Традиции предлагаются как образовательные рамки для размышления — никогда как медицинские утверждения — и везде помечены соответствующе.", es:"Cada recomendación se remonta a evidencia revisada por pares. Las tradiciones se ofrecen como marcos educativos para reflexionar, nunca como afirmaciones médicas, y se etiquetan así en todo momento.", fr:"Chaque recommandation remonte à des preuves évaluées par les pairs. Les traditions sont proposées comme cadres éducatifs de réflexion — jamais comme allégations médicales — et signalées comme telles partout.", de:"Jede Empfehlung geht auf begutachtete Evidenz zurück. Traditionen werden als erzieherische Reflexionsrahmen angeboten — nie als medizinische Aussagen — und überall so gekennzeichnet." },
    "Studies in the evidence base": { he:"מחקרים בבסיס הראיות", ar:"دراسات في قاعدة الأدلّة", ru:"Исследований в доказательной базе", es:"Estudios en la base de evidencia", fr:"Études dans la base de preuves", de:"Studien in der Evidenzbasis" },
    "Weighted scoring model": { he:"מודל ניקוד משוקלל", ar:"نموذج تسجيل مرجّح", ru:"Взвешенная модель оценки", es:"Modelo de puntuación ponderada", fr:"Modèle de score pondéré", de:"Gewichtetes Bewertungsmodell" },
    "Advisory board": { he:"מועצה מייעצת", ar:"المجلس الاستشاري", ru:"Консультативный совет", es:"Consejo asesor", fr:"Conseil consultatif", de:"Beirat" },
    "Metabolic medicine": { he:"רפואה מטבולית", ar:"طب الأيض", ru:"Метаболическая медицина", es:"Medicina metabólica", fr:"Médecine métabolique", de:"Stoffwechselmedizin" },
    "Sleep & circadian science": { he:"מדע השינה והמקצב הצירקדי", ar:"علم النوم والإيقاع اليومي", ru:"Наука сна и циркадных ритмов", es:"Ciencia del sueño y circadiana", fr:"Science du sommeil et circadienne", de:"Schlaf- & zirkadiane Wissenschaft" },
    "Traditional medicine ethics": { he:"אתיקה של רפואה מסורתית", ar:"أخلاقيات الطب التقليدي", ru:"Этика традиционной медицины", es:"Ética de la medicina tradicional", fr:"Éthique des médecines traditionnelles", de:"Ethik traditioneller Medizin" },

    /* PRICING */
    "Plans": { he:"מסלולים", ar:"الخطط", ru:"Тарифы", es:"Planes", fr:"Forfaits", de:"Pläne" },
    "Start whole. Grow from there.": { he:"להתחיל שלם. לצמוח משם.", ar:"ابدأ متكاملًا. وانمُ من هناك.", ru:"Начните целостно. Растите дальше.", es:"Empieza entero. Crece desde ahí.", fr:"Commencez entier. Évoluez ensuite.", de:"Ganz beginnen. Von dort wachsen." },
    "Free": { he:"חינם", ar:"مجاني", ru:"Бесплатно", es:"Gratis", fr:"Gratuit", de:"Kostenlos" },
    "The assessment and your core balance portrait.": { he:"ההערכה ודיוקן האיזון המרכזי שלך.", ar:"التقييم وصورة توازنك الأساسية.", ru:"Оценка и базовый портрет баланса.", es:"La evaluación y tu retrato de equilibrio básico.", fr:"Le bilan et votre portrait d'équilibre de base.", de:"Die Analyse und Ihr Kern-Balance-Porträt." },
    "Get started": { he:"להתחיל", ar:"ابدأ الآن", ru:"Начать", es:"Empezar", fr:"Commencer", de:"Loslegen" },
    "Full assessment": { he:"הערכה מלאה", ar:"تقييم كامل", ru:"Полная оценка", es:"Evaluación completa", fr:"Bilan complet", de:"Vollständige Analyse" },
    "6 wellness scores": { he:"6 ציוני בריאות", ar:"6 نقاط عافية", ru:"6 оценок благополучия", es:"6 puntuaciones de bienestar", fr:"6 scores de bien-être", de:"6 Wellness-Werte" },
    "One tradition lens": { he:"עדשת מסורת אחת", ar:"عدسة تقليدٍ واحد", ru:"Одна линза-традиция", es:"Una lente de tradición", fr:"Une lentille de tradition", de:"Eine Traditions-Linse" },
    "Most loved": { he:"האהוב ביותר", ar:"الأكثر تفضيلًا", ru:"Любимый выбор", es:"El más elegido", fr:"Le plus aimé", de:"Am beliebtesten" },
    "Premium": { he:"פרימיום", ar:"بريميوم", ru:"Премиум", es:"Premium", fr:"Premium", de:"Premium" },
    "Every tradition, the AI coach, and Swarga mode.": { he:"כל מסורת, מאמן ה-AI ומצב סווארגה.", ar:"كل التقاليد، ومدرّب الذكاء الاصطناعي، ووضع سوارغا.", ru:"Все традиции, ИИ-коуч и режим Swarga.", es:"Todas las tradiciones, el coach de IA y el modo Swarga.", fr:"Toutes les traditions, le coach IA et le mode Swarga.", de:"Alle Traditionen, der KI-Coach und der Swarga-Modus." },
    "Start 14-day trial": { he:"להתחיל ניסיון של 14 יום", ar:"ابدأ تجربة 14 يومًا", ru:"14 дней бесплатно", es:"Prueba de 14 días", fr:"Essai de 14 jours", de:"14 Tage testen" },
    "All 7 traditions + Swarga": { he:"כל 7 המסורות + סווארגה", ar:"كل التقاليد السبعة + سوارغا", ru:"Все 7 традиций + Swarga", es:"Las 7 tradiciones + Swarga", fr:"Les 7 traditions + Swarga", de:"Alle 7 Traditionen + Swarga" },
    "AI integrative coach": { he:"מאמן אינטגרטיבי AI", ar:"مدرّب تكاملي بالذكاء الاصطناعي", ru:"ИИ интегративный коуч", es:"Coach integrativo de IA", fr:"Coach intégratif IA", de:"KI-Integrativ-Coach" },
    "Wearable + lab sync": { he:"סנכרון מכשירים לבישים + מעבדה", ar:"مزامنة الأجهزة + التحاليل", ru:"Синхр. устройств и анализов", es:"Sincr. wearables + analíticas", fr:"Sync objets + analyses", de:"Wearable- + Labor-Sync" },
    "Daily adaptive plans": { he:"תוכניות יומיות מסתגלות", ar:"خطط يومية متكيّفة", ru:"Ежедневные адаптивные планы", es:"Planes diarios adaptativos", fr:"Plans quotidiens adaptatifs", de:"Tägliche adaptive Pläne" },
    "Practitioner": { he:"מטפל", ar:"ممارس", ru:"Специалист", es:"Profesional", fr:"Praticien", de:"Fachperson" },
    "For coaches managing a roster of clients.": { he:"למאמנים המנהלים מגוון לקוחות.", ar:"للمدرّبين الذين يديرون قائمة عملاء.", ru:"Для коучей с пулом клиентов.", es:"Para coaches con una cartera de clientes.", fr:"Pour les coachs gérant un portefeuille de clients.", de:"Für Coaches mit mehreren Klienten." },
    "Start trial": { he:"להתחיל ניסיון", ar:"ابدأ التجربة", ru:"Начать пробный период", es:"Probar", fr:"Essayer", de:"Test starten" },
    "Up to 25 clients": { he:"עד 25 לקוחות", ar:"حتى 25 عميلًا", ru:"До 25 клиентов", es:"Hasta 25 clientes", fr:"Jusqu'à 25 clients", de:"Bis zu 25 Klienten" },
    "Client dashboards": { he:"לוחות בקרה ללקוחות", ar:"لوحات تحكّم العملاء", ru:"Панели клиентов", es:"Paneles de clientes", fr:"Tableaux de bord clients", de:"Klienten-Dashboards" },
    "Protocol builder": { he:"בונה פרוטוקולים", ar:"منشئ البروتوكولات", ru:"Конструктор протоколов", es:"Creador de protocolos", fr:"Créateur de protocoles", de:"Protokoll-Baukasten" },
    "Clinic": { he:"מרפאה", ar:"عيادة", ru:"Клиника", es:"Clínica", fr:"Clinique", de:"Klinik" },
    "Multi-practitioner teams and care groups.": { he:"צוותים רב-מטפליים וקבוצות טיפול.", ar:"فرق متعددة الممارسين ومجموعات رعاية.", ru:"Команды специалистов и группы ухода.", es:"Equipos multiprofesionales y grupos de cuidado.", fr:"Équipes pluri-praticiens et groupes de soin.", de:"Teams mehrerer Fachkräfte und Pflegegruppen." },
    "Contact sales": { he:"ליצירת קשר עם המכירות", ar:"تواصل مع المبيعات", ru:"Связаться с отделом продаж", es:"Contactar ventas", fr:"Contacter les ventes", de:"Vertrieb kontaktieren" },
    "Unlimited clients": { he:"לקוחות ללא הגבלה", ar:"عملاء بلا حدود", ru:"Безлимит клиентов", es:"Clientes ilimitados", fr:"Clients illimités", de:"Unbegrenzte Klienten" },
    "Team roles + audit": { he:"תפקידי צוות + ביקורת", ar:"أدوار الفريق + تدقيق", ru:"Роли команды + аудит", es:"Roles de equipo + auditoría", fr:"Rôles d'équipe + audit", de:"Teamrollen + Audit" },
    "HIPAA-ready": { he:"מוכן ל-HIPAA", ar:"متوافق مع HIPAA", ru:"Готовность к HIPAA", es:"Preparado para HIPAA", fr:"Compatible HIPAA", de:"HIPAA-bereit" },
    "Corporate": { he:"ארגוני", ar:"للشركات", ru:"Для компаний", es:"Corporativo", fr:"Entreprise", de:"Unternehmen" },
    "Custom": { he:"מותאם אישית", ar:"مخصّص", ru:"Индивидуально", es:"A medida", fr:"Sur mesure", de:"Individuell" },
    "Whole-org wellbeing at scale.": { he:"רווחה ארגונית בקנה מידה רחב.", ar:"عافية المؤسسة بالكامل وعلى نطاق واسع.", ru:"Благополучие всей организации в масштабе.", es:"Bienestar de toda la organización a escala.", fr:"Bien-être de toute l'organisation à grande échelle.", de:"Wohlbefinden der gesamten Organisation im großen Maßstab." },
    "Talk to us": { he:"לדבר איתנו", ar:"تحدّث إلينا", ru:"Связаться с нами", es:"Habla con nosotros", fr:"Parlez-nous", de:"Sprechen Sie uns an" },
    "SSO + admin": { he:"SSO + ניהול", ar:"الدخول الموحّد + إدارة", ru:"SSO + админ", es:"SSO + administración", fr:"SSO + admin", de:"SSO + Admin" },
    "Aggregate insights": { he:"תובנות מצרפיות", ar:"رؤى مجمّعة", ru:"Сводная аналитика", es:"Información agregada", fr:"Analyses agrégées", de:"Aggregierte Einblicke" },
    "Dedicated success": { he:"ליווי הצלחה ייעודי", ar:"دعم نجاحٍ مخصّص", ru:"Персональный менеджер успеха", es:"Éxito dedicado", fr:"Accompagnement dédié", de:"Dedizierter Erfolg" },

    /* FAQ */
    "Questions": { he:"שאלות", ar:"أسئلة", ru:"Вопросы", es:"Preguntas", fr:"Questions", de:"Fragen" },
    "Good to know.": { he:"כדאי לדעת.", ar:"معلوماتٌ مفيدة.", ru:"Полезно знать.", es:"Bueno saberlo.", fr:"Bon à savoir.", de:"Gut zu wissen." },
    "Is Holos a medical product?": { he:"האם הולוס הוא מוצר רפואי?", ar:"هل هولوس منتجٌ طبي؟", ru:"Holos — это медицинский продукт?", es:"¿Es Holos un producto médico?", fr:"Holos est-il un produit médical ?", de:"Ist Holos ein medizinisches Produkt?" },
    "No. Holos is a wellness and education platform. Our recommendations are grounded in peer-reviewed science, and the wisdom traditions are offered as educational frameworks for self-reflection — not diagnosis or treatment. Always consult a clinician for medical concerns.": { he:"לא. הולוס היא פלטפורמת בריאות וחינוך. ההמלצות שלנו מבוססות על מדע שעבר ביקורת עמיתים, ומסורות החוכמה מוצעות כמסגרות חינוכיות להתבוננות עצמית — לא לאבחון או טיפול. תמיד התייעצו עם רופא בנושאים רפואיים.", ar:"لا. هولوس منصة عافية وتعليم. توصياتنا قائمة على علمٍ محكَّم، وتُقدَّم تقاليد الحكمة كأُطرٍ تعليميةٍ للتأمّل الذاتي — لا للتشخيص أو العلاج. استشر طبيبًا دائمًا في الأمور الطبية.", ru:"Нет. Holos — платформа благополучия и образования. Наши рекомендации основаны на рецензируемой науке, а традиции мудрости предлагаются как образовательные рамки для саморефлексии, а не диагностики или лечения. По медицинским вопросам всегда обращайтесь к врачу.", es:"No. Holos es una plataforma de bienestar y educación. Nuestras recomendaciones se basan en ciencia revisada por pares, y las tradiciones se ofrecen como marcos educativos de autorreflexión, no de diagnóstico ni tratamiento. Consulta siempre a un médico ante dudas de salud.", fr:"Non. Holos est une plateforme de bien-être et d'éducation. Nos recommandations reposent sur une science évaluée par les pairs, et les traditions sont proposées comme cadres éducatifs d'introspection — non de diagnostic ou de traitement. Consultez toujours un médecin pour toute question de santé.", de:"Nein. Holos ist eine Wellness- und Bildungsplattform. Unsere Empfehlungen beruhen auf begutachteter Wissenschaft, und die Weisheitstraditionen dienen als erzieherische Rahmen zur Selbstreflexion — nicht zur Diagnose oder Behandlung. Wenden Sie sich bei medizinischen Anliegen stets an eine Ärztin oder einen Arzt." },
    "How are the ancient traditions handled respectfully?": { he:"כיצד מטופלות המסורות העתיקות בכבוד?", ar:"كيف تُعامَل التقاليد القديمة باحترام؟", ru:"Как уважительно обходятся с древними традициями?", es:"¿Cómo se tratan las tradiciones antiguas con respeto?", fr:"Comment les traditions anciennes sont-elles traitées avec respect ?", de:"Wie wird respektvoll mit den alten Traditionen umgegangen?" },
    "Each tradition is presented educationally, with its origin and context, and reviewed by advisors versed in that practice. We never claim clinical efficacy for traditional frameworks — they're lenses for understanding, always shown alongside the evidence base.": { he:"כל מסורת מוצגת באופן חינוכי, עם מקורה והקשרה, ונבדקת על ידי יועצים הבקיאים בפרקטיקה. איננו טוענים ליעילות קלינית של מסגרות מסורתיות — הן עדשות להבנה, ותמיד מוצגות לצד בסיס הראיות.", ar:"يُقدَّم كل تقليد تعليميًّا، مع أصله وسياقه، ويراجعه مستشارون متمكّنون من تلك الممارسة. ولا ندّعي فعّاليةً سريريةً للأُطر التقليدية — فهي عدساتٌ للفهم، تُعرض دائمًا إلى جانب قاعدة الأدلّة.", ru:"Каждая традиция представлена в образовательном ключе, с её происхождением и контекстом, и проверена консультантами, сведущими в этой практике. Мы никогда не заявляем о клинической эффективности традиционных систем — это линзы для понимания, всегда показанные рядом с доказательной базой.", es:"Cada tradición se presenta de forma educativa, con su origen y contexto, y la revisan asesores expertos en esa práctica. Nunca afirmamos eficacia clínica de los marcos tradicionales: son lentes para comprender, siempre junto a la base de evidencia.", fr:"Chaque tradition est présentée de façon éducative, avec son origine et son contexte, et revue par des conseillers versés dans cette pratique. Nous n'alléguons jamais d'efficacité clinique pour les cadres traditionnels — ce sont des lentilles de compréhension, toujours montrées aux côtés des preuves.", de:"Jede Tradition wird erzieherisch, mit Ursprung und Kontext, dargestellt und von Beratern geprüft, die in dieser Praxis bewandert sind. Wir behaupten nie klinische Wirksamkeit traditioneller Rahmen — sie sind Linsen des Verstehens, stets neben der Evidenzbasis gezeigt." },
    "What is Swarga Integral mode?": { he:"מהו מצב סווארגה אינטגרל?", ar:"ما هو وضع سوارغا التكاملي؟", ru:"Что такое режим Swarga Integral?", es:"¿Qué es el modo Swarga Integral?", fr:"Qu'est-ce que le mode Swarga Integral ?", de:"Was ist der Swarga-Integral-Modus?" },
    "Swarga is our proprietary synthesis — eleven dimensions that fuse physical, energetic, emotional, mental, relational, and existential wellbeing with dosha and five-element models into one living portrait. It's the flagship lens, available on Premium and above.": { he:"סווארגה היא הסינתזה הקניינית שלנו — אחד-עשר מימדים הממזגים רווחה פיזית, אנרגטית, רגשית, מנטלית, יחסית וקיומית עם מודלים של דושה וחמשת היסודות לכדי דיוקן חי אחד. זוהי עדשת הדגל, זמינה בפרימיום ומעלה.", ar:"سوارغا هي خلاصتنا الخاصة — أحد عشر بُعدًا تدمج العافية الجسدية والطاقية والعاطفية والذهنية والعلائقية والوجودية مع نماذج الدوشا والعناصر الخمسة في صورةٍ حيّةٍ واحدة. إنها عدستنا الرائدة، متاحة في بريميوم وما فوق.", ru:"Swarga — наш собственный синтез: одиннадцать измерений, сливающих физическое, энергетическое, эмоциональное, ментальное, социальное и экзистенциальное благополучие с моделями доши и пяти элементов в один живой портрет. Это флагманская линза, доступная в Премиуме и выше.", es:"Swarga es nuestra síntesis propia: once dimensiones que funden el bienestar físico, energético, emocional, mental, relacional y existencial con los modelos de dosha y cinco elementos en un retrato vivo. Es la lente insignia, disponible en Premium y superior.", fr:"Swarga est notre synthèse propriétaire — onze dimensions qui fondent le bien-être physique, énergétique, émotionnel, mental, relationnel et existentiel avec les modèles dosha et cinq éléments en un portrait vivant. C'est la lentille phare, disponible à partir de Premium.", de:"Swarga ist unsere eigene Synthese — elf Dimensionen, die körperliches, energetisches, emotionales, mentales, relationales und existenzielles Wohlbefinden mit Dosha- und Fünf-Elemente-Modellen zu einem lebendigen Porträt verbinden. Es ist die Flaggschiff-Linse, verfügbar ab Premium." },
    "Which languages and themes are supported?": { he:"אילו שפות וערכות נושא נתמכות?", ar:"ما اللغات والسمات المدعومة؟", ru:"Какие языки и темы поддерживаются?", es:"¿Qué idiomas y temas se admiten?", fr:"Quelles langues et quels thèmes sont pris en charge ?", de:"Welche Sprachen und Themes werden unterstützt?" },
    "Seven languages including full right-to-left support for Hebrew and Arabic, with RTL-aware navigation and dashboards. Five visual themes — Modern Clinical, Holistic Wellness, Ancient Wisdom, Executive Premium, and Dark — all share one design system. Try the light/dark toggle in the nav.": { he:"שבע שפות כולל תמיכה מלאה מימין-לשמאל לעברית ולערבית, עם ניווט ולוחות בקרה מותאמי RTL. חמש ערכות נושא — קליני מודרני, בריאות הוליסטית, חוכמה עתיקה, פרימיום ניהולי וכהה — כולן חולקות מערכת עיצוב אחת. נסו את מתג הבהיר/כהה בתפריט.", ar:"سبع لغات تشمل دعمًا كاملًا للكتابة من اليمين إلى اليسار للعبرية والعربية، مع تنقّلٍ ولوحاتٍ متوافقة مع RTL. خمس سمات بصرية — سريري حديث، عافية شاملة، حكمة قديمة، بريميوم تنفيذي، وداكن — تشترك جميعها في نظام تصميمٍ واحد. جرّب مفتاح الفاتح/الداكن في الشريط.", ru:"Семь языков, включая полную поддержку письма справа налево для иврита и арабского, с RTL-навигацией и дашбордами. Пять визуальных тем — Modern Clinical, Holistic Wellness, Ancient Wisdom, Executive Premium и Dark — используют одну дизайн-систему. Попробуйте переключатель светлая/тёмная в меню.", es:"Siete idiomas, con soporte completo de derecha a izquierda para hebreo y árabe, y navegación y paneles adaptados a RTL. Cinco temas visuales —Modern Clinical, Holistic Wellness, Ancient Wisdom, Executive Premium y Dark— comparten un mismo sistema de diseño. Prueba el interruptor claro/oscuro en el menú.", fr:"Sept langues, avec une prise en charge complète de l'écriture de droite à gauche pour l'hébreu et l'arabe, navigation et tableaux de bord adaptés au RTL. Cinq thèmes visuels — Modern Clinical, Holistic Wellness, Ancient Wisdom, Executive Premium et Dark — partagent un même système de design. Essayez le commutateur clair/sombre dans la barre.", de:"Sieben Sprachen inklusive voller Rechts-nach-links-Unterstützung für Hebräisch und Arabisch, mit RTL-fähiger Navigation und Dashboards. Fünf visuelle Themes — Modern Clinical, Holistic Wellness, Ancient Wisdom, Executive Premium und Dark — teilen ein Designsystem. Probieren Sie den Hell/Dunkel-Schalter in der Leiste." },
    "Can I cancel anytime?": { he:"האם אפשר לבטל בכל עת?", ar:"هل يمكنني الإلغاء في أي وقت؟", ru:"Можно отменить в любой момент?", es:"¿Puedo cancelar cuando quiera?", fr:"Puis-je annuler à tout moment ?", de:"Kann ich jederzeit kündigen?" },
    "Yes — monthly plans cancel in one tap, no questions asked. Your portrait and history stay exportable, and the Free tier remains yours forever.": { he:"כן — מסלולים חודשיים מתבטלים בנגיעה אחת, ללא שאלות. הדיוקן וההיסטוריה שלך נשארים ניתנים לייצוא, והמסלול החינמי נשאר שלך לתמיד.", ar:"نعم — تُلغى الخطط الشهرية بنقرةٍ واحدة دون أسئلة. تبقى صورتك وسجلّك قابلَين للتصدير، ويبقى المستوى المجاني لك إلى الأبد.", ru:"Да — месячные планы отменяются в одно касание, без вопросов. Ваш портрет и история остаются доступными для экспорта, а бесплатный тариф навсегда ваш.", es:"Sí: los planes mensuales se cancelan con un toque, sin preguntas. Tu retrato e historial siguen siendo exportables y el plan gratuito es tuyo para siempre.", fr:"Oui — les forfaits mensuels s'annulent en un geste, sans question. Votre portrait et votre historique restent exportables, et l'offre gratuite reste vôtre pour toujours.", de:"Ja — Monatspläne kündigen Sie mit einem Tippen, ohne Nachfragen. Ihr Porträt und Verlauf bleiben exportierbar, und die kostenlose Stufe gehört für immer Ihnen." },

    /* FINAL CTA */
    "Begin": { he:"להתחיל", ar:"ابدأ", ru:"Начать", es:"Comienza", fr:"Commencer", de:"Beginnen" },
    "Meet the whole of you.": { he:"הכירו את כל כולכם.", ar:"تعرّف على كلّك أنت.", ru:"Познакомьтесь с собой целиком.", es:"Conoce tu ser completo.", fr:"Rencontrez votre être entier.", de:"Begegnen Sie sich ganz." },
    "Take the assessment free. In ten minutes, see yourself the way every great tradition — and the latest science — would.": { he:"בצעו את ההערכה בחינם. בעשר דקות, ראו את עצמכם כפי שכל מסורת גדולה — והמדע העדכני — היו רואים.", ar:"أجرِ التقييم مجانًا. في عشر دقائق، انظر إلى نفسك كما يراك كل تقليدٍ عظيم — وأحدث العلم.", ru:"Пройдите оценку бесплатно. За десять минут увидьте себя так, как увидела бы каждая великая традиция — и новейшая наука.", es:"Haz la evaluación gratis. En diez minutos, mírate como lo haría cada gran tradición y la ciencia más reciente.", fr:"Faites le bilan gratuitement. En dix minutes, voyez-vous comme le ferait chaque grande tradition — et la science la plus récente.", de:"Machen Sie die Analyse kostenlos. In zehn Minuten sehen Sie sich, wie jede große Tradition — und die neueste Wissenschaft — es täte." },
    "Book a demo": { he:"לקבוע הדגמה", ar:"احجز عرضًا توضيحيًا", ru:"Заказать демо", es:"Reservar demo", fr:"Réserver une démo", de:"Demo buchen" },

    /* FOOTER */
    "Integrative wellness intelligence. Modern science, ancient wisdom, one whole you.": { he:"בינת בריאות אינטגרטיבית. מדע מודרני, חוכמה עתיקה, אדם שלם אחד.", ar:"ذكاء العافية التكاملي. علمٌ حديث، حكمةٌ قديمة، أنت الواحد المتكامل.", ru:"Интегративный интеллект благополучия. Современная наука, древняя мудрость, один целостный вы.", es:"Inteligencia de bienestar integrativa. Ciencia moderna, sabiduría antigua, un tú completo.", fr:"Intelligence de bien-être intégrative. Science moderne, sagesse ancienne, un vous entier.", de:"Integrative Wellness-Intelligenz. Moderne Wissenschaft, alte Weisheit, ein ganzes Ich." },
    "Company": { he:"חברה", ar:"الشركة", ru:"Компания", es:"Empresa", fr:"Entreprise", de:"Unternehmen" },
    "Resources": { he:"משאבים", ar:"موارد", ru:"Ресурсы", es:"Recursos", fr:"Ressources", de:"Ressourcen" },
    "Legal": { he:"משפטי", ar:"قانوني", ru:"Правовое", es:"Legal", fr:"Mentions légales", de:"Rechtliches" },
    "Assessment": { he:"הערכה", ar:"التقييم", ru:"Оценка", es:"Evaluación", fr:"Bilan", de:"Analyse" },
    "AI coach": { he:"מאמן AI", ar:"مدرّب الذكاء الاصطناعي", ru:"ИИ-коуч", es:"Coach de IA", fr:"Coach IA", de:"KI-Coach" },
    "About": { he:"אודות", ar:"من نحن", ru:"О нас", es:"Sobre nosotros", fr:"À propos", de:"Über uns" },
    "Careers": { he:"קריירה", ar:"وظائف", ru:"Карьера", es:"Empleo", fr:"Carrières", de:"Karriere" },
    "Press": { he:"עיתונות", ar:"الصحافة", ru:"Пресса", es:"Prensa", fr:"Presse", de:"Presse" },
    "Journal": { he:"בלוג", ar:"المدوّنة", ru:"Журнал", es:"Revista", fr:"Journal", de:"Journal" },
    "Help center": { he:"מרכז עזרה", ar:"مركز المساعدة", ru:"Центр помощи", es:"Centro de ayuda", fr:"Centre d'aide", de:"Hilfe-Center" },
    "For practitioners": { he:"למטפלים", ar:"للممارسين", ru:"Для специалистов", es:"Para profesionales", fr:"Pour les praticiens", de:"Für Fachkräfte" },
    "Privacy": { he:"פרטיות", ar:"الخصوصية", ru:"Конфиденциальность", es:"Privacidad", fr:"Confidentialité", de:"Datenschutz" },
    "Terms": { he:"תנאים", ar:"الشروط", ru:"Условия", es:"Términos", fr:"Conditions", de:"AGB" },
    "Medical disclaimer": { he:"הסרת אחריות רפואית", ar:"إخلاء مسؤولية طبية", ru:"Медицинская оговорка", es:"Aviso médico", fr:"Avertissement médical", de:"Medizinischer Hinweis" },
    "Accessibility": { he:"נגישות", ar:"إمكانية الوصول", ru:"Доступность", es:"Accesibilidad", fr:"Accessibilité", de:"Barrierefreiheit" },
    "Not a medical device · Wellness & education only": { he:"לא מכשיר רפואי · בריאות וחינוך בלבד", ar:"ليس جهازًا طبيًّا · عافية وتعليم فقط", ru:"Не медицинское устройство · Только благополучие и образование", es:"No es un dispositivo médico · Solo bienestar y educación", fr:"Pas un dispositif médical · Bien-être et éducation uniquement", de:"Kein Medizinprodukt · Nur Wellness & Bildung" }
  };

  /* ---- build per-language reverse maps ---- */
  var LANGS = ["he","ar","ru","es","fr","de"];
  var DICT = {};
  LANGS.forEach(function (l) { DICT[l] = {}; });
  Object.keys(T).forEach(function (en) {
    LANGS.forEach(function (l) {
      var v = T[en][l];
      if (v) DICT[l][en] = v;
    });
  });

  /* ---- collect translatable text nodes ---- */
  var cache = null;
  function shouldSkip(node) {
    var p = node.parentNode;
    if (!p) return true;
    if (p.closest('script,style,svg,.lang-menu,.brand,[data-no-i18n]')) return true;
    return false;
  }
  function collect() {
    cache = [];
    var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode: function (n) {
        if (!n.nodeValue || !n.nodeValue.trim()) return NodeFilter.FILTER_REJECT;
        if (shouldSkip(n)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    var n;
    while ((n = walker.nextNode())) {
      var orig = n.nodeValue;
      var m = orig.match(/^(\s*)([\s\S]*?)(\s*)$/);
      cache.push({ node: n, orig: orig, lead: m[1], core: m[2].replace(/\s+/g, ' '), trail: m[3] });
    }
  }

  function apply(lang) {
    if (!cache) collect();
    var dict = DICT[lang];
    cache.forEach(function (it) {
      if (lang === 'en' || !dict || !dict[it.core]) {
        if (it.node.nodeValue !== it.orig) it.node.nodeValue = it.orig;
      } else {
        it.node.nodeValue = it.lead + dict[it.core] + it.trail;
      }
    });
    var html = document.documentElement;
    html.lang = lang;
    html.dir = RTL[lang] ? 'rtl' : 'ltr';
    var label = document.querySelector('[data-lang-label]');
    if (label) label.textContent = lang.toUpperCase();
    document.querySelectorAll('[data-lang]').forEach(function (b) {
      b.classList.toggle('active', b.getAttribute('data-lang') === lang);
    });
    try { localStorage.setItem('holos-lang', lang); } catch (e) {}
  }

  window.HolosI18n = { set: apply };

  /* ---- init from storage ---- */
  function init() {
    var saved = 'en';
    try { saved = localStorage.getItem('holos-lang') || 'en'; } catch (e) {}
    if (saved && saved !== 'en') apply(saved);
    else { document.documentElement.lang = 'en'; document.documentElement.dir = 'ltr'; }
  }
  if (document.readyState !== 'loading') init();
  else document.addEventListener('DOMContentLoaded', init);
})();
