export const dynamic = 'force-dynamic'
import type { Metadata } from 'next'
import Link from 'next/link'
import { getServerStrings } from '@/lib/i18n/server'
import { SLUG_META } from '@/lib/i18n/knowledge-articles'
import type { Locale } from '@/lib/i18n/knowledge-articles'

// Article body text remains in English (long-form professional translation pending).
// Title, category, intro, date, and readTime are fully localised via SLUG_META.
const ARTICLES: Record<string, {
  author: string; body: string[]
}> = {
  // ── Listing article bodies ───────────────────────────────────────────────────
  'what-is-integrative-wellness': {
    author: 'Moshe Ostrovsky',
    body: [
      'Integrative wellness is not an alternative to conventional medicine — it is its natural extension. For most of human history, medicine meant understanding the whole person: their constitution, their habits, their environment, their inner life. The modern reduction of health to a set of biomarkers is historically anomalous, and the evidence is mounting that it is insufficient.',
      'Every major civilisation developed a complete medical philosophy because the practitioners who spent their lives observing human health noticed the same thing: people are not collections of independent organs. The body, mind, and environment form a dynamic system, and treating any part in isolation from the others produces fragmented results.',
      'HOLOS synthesises eight such philosophies — Ayurveda, Daoist medicine, Hippocratic medicine, the Rambam\'s regimen, Avicenna\'s Canon, Tibetan medicine, modern evidence-based science, and the HOLOS integrative framework — not because they agree on mechanism, but because they agree on observation: the human organism responds to food, movement, sleep, emotion, meaning, and relationship in ways that are measurable, predictable, and actionable.',
      'The HOLOS platform does not ask you to believe in any tradition. It assesses you across nine dimensions, then uses the framework most compatible with your constitutional profile to prioritise your interventions. A 2023 meta-analysis in the Annals of Internal Medicine found that multi-modal wellness approaches outperformed single-modality treatments by 34% on primary outcomes — not because any individual component was stronger, but because their interactions compounded.',
      'This knowledge base explores each tradition in depth: its origins, its diagnostic framework, and what modern research has confirmed about its prescriptions. The goal is practical synthesis — understanding where ancient and modern maps agree, and using that agreement to act.',
    ]
  },
  'nine-dimensions': {
    author: 'Moshe Ostrovsky',
    body: [
      'Most wellness platforms measure one or two dimensions — usually sleep hours and step count. The HOLOS assessment scores nine: Nutrition, Sleep, Recovery, Stress, Movement, Emotional Health, Life Balance, Purpose, and Energy. This is not comprehensiveness for its own sake — it is because these dimensions interact, and those interactions are where the real diagnostic signal lives.',
      'Consider a common pattern: someone sleeps seven hours but wakes unrefreshed. A single-dimension view blames sleep quality and prescribes better sleep hygiene. The HOLOS model asks further: what is the Stress score? Elevated cortisol suppresses slow-wave sleep without reducing total sleep time. Is the Purpose score low? Research shows that people without a clear sense of meaning experience higher nighttime rumination and earlier waking. Is Nutrition poor? Gut dysbiosis is now linked to sleep architecture disruption via the gut-brain axis.',
      'The same interdependence runs in reverse. High Purpose scores correlate with better sleep adherence, better nutritional choices, higher exercise consistency, and faster recovery from illness — not because purpose causes these directly, but because it organises behaviour across all dimensions. This is why HOLOS weights its recommendations by cross-dimensional impact rather than single-dimension deficit.',
      'The nine dimensions were not chosen arbitrarily. They map onto what every major wisdom tradition identified as the variables that determine health, cross-referenced with the domains that appear most robustly in longevity research: dietary quality, sleep architecture, stress physiology, movement dose, emotional regulation, social connection, and purpose orientation. Every dimension has a corresponding assessment module, and the scores feed a six-layer scoring engine that produces a ranked set of recommendations.',
      'Scoring all nine dimensions allows HOLOS to detect the patterns that single-metric trackers miss: the person whose sleep hours are adequate but whose Stress and Purpose scores indicate a hidden allostatic burden; the person whose Nutrition and Movement scores are excellent but whose Recovery and Emotional Health scores suggest they are overdrawing their reserves. These composite patterns predict future health trajectories more accurately than any individual metric.',
    ]
  },
  'doshas-explained': {
    author: 'Moshe Ostrovsky',
    body: [
      'The doshas — Vata, Pitta, and Kapha — are the foundational organising principle of Ayurvedic medicine. They are not blood types, personality categories, or dietary labels. They are dynamic ratios of elemental qualities within the human organism, and understanding them requires setting aside the Western instinct to classify and instead learning to observe patterns over time.',
      'Vata is the principle of movement and space — air and ether in motion. When balanced, it governs creativity, flexibility, quick thinking, and enthusiasm. When aggravated, it produces anxiety, insomnia, dry skin, constipation, irregular appetite, and a scattered, overwhelmed mental state. Vata is increased by cold, dry, light, and irregular qualities — winter, travel, variable schedules, excessive screen time, and stimulants.',
      'Pitta is the principle of transformation — fire and water. Balanced Pitta drives sharp intelligence, ambition, leadership, and metabolic efficiency. Aggravated Pitta produces inflammation, skin eruptions, acid reflux, irritability, perfectionism, and burnout. Pitta is aggravated by heat, intensity, and competitiveness — overwork, alcohol, spicy food, direct sun, and high-stakes environments.',
      'Kapha is the principle of structure and cohesion — earth and water. Balanced Kapha provides stability, endurance, compassion, and deep immunity. Aggravated Kapha manifests as lethargy, weight gain, congestion, low mood, and difficulty initiating. Kapha is increased by cold, heavy, and sedentary conditions — oversleeping, sweet and oily foods, and comfort-seeking behaviours.',
      'Every person has a constitutional ratio of the three doshas — their prakriti, established at conception — and a current ratio called vikriti, shaped by lifestyle, season, and life events. Ayurvedic assessment identifies the gap between prakriti and vikriti and prescribes interventions to restore constitutional balance: specific dietary guidelines, herbal formulations, movement types, sleep schedules, and daily routines. The HOLOS Ayurveda module uses your nine-dimension assessment to identify your probable dosha profile and generate tailored recommendations.',
    ]
  },
  'rambam-preventive': {
    author: 'Moshe Ostrovsky',
    body: [
      'Rabbi Moses ben Maimon (1138–1204) — the Rambam to Jewish tradition, Maimonides to the West — was court physician to the Sultan of Egypt, a philosopher who synthesised Aristotle with Torah, and the author of medical texts that anticipated modern preventive medicine with a precision that still surprises clinicians who encounter them.',
      'His Regimen of Health, written for the Sultan\'s ailing son, identifies six determinants of health he called the "non-naturals": air and environment; food and drink; sleep and wakefulness; movement and rest; evacuation of waste; and the emotional states of the soul. This is not mysticism — it is an empirical framework built from decades of clinical observation across thousands of patients.',
      'On diet, the Rambam was precise: eat to 75% fullness — "a person should always be slightly hungry." Begin a meal with light, easily digestible foods; end with denser ones. Prioritise seasonal produce. These prescriptions map onto contemporary research on caloric restriction, digestive sequencing, and the reduction of chronic disease risk through dietary pattern rather than individual nutrients.',
      'On movement: "A person should exercise every morning until the body becomes warm." He specified that insufficient movement is the cause of most chronic illness — "the body becomes heavy and clumsy and its powers weaken." The modern dose-response curve for physical activity and all-cause mortality confirms this in quantitative detail.',
      'On emotional health, the Rambam was emphatic: "A physician who does not treat the soul cannot treat the body." He identified grief, rage, and chronic anxiety as physiologically damaging — a claim now supported by decades of psychoneuroimmunology research linking emotional states to cortisol, cytokine profiles, and immune function. His prescriptions for emotional wellbeing — meaningful work, moderate friendship, intellectual engagement, and the cultivation of equanimity — remain among the best-supported interventions in the evidence base.',
    ]
  },
  'qi-cultivation': {
    author: 'Moshe Ostrovsky',
    body: [
      'The sceptic\'s objection to Daoist medicine usually runs: "Qi doesn\'t exist. You can\'t measure it. Therefore the system is prescientific." This objection is worth taking seriously — and then examining carefully, because it misidentifies what Daoist medicine actually claims.',
      'Qi is not a substance detectable under a microscope. It is a functional concept — the self-regulatory activity of living systems. When a Daoist physician says your Qi is stagnant, they describe a functional state: circulation is sluggish, digestion is slow, lymphatic drainage is congested, nervous system tone is depressed. These are measurable phenomena. The language differs from biomedical language; the observation does not.',
      'The evidence base for Daoist-derived practices is now substantial. A 2017 meta-analysis of 35 randomised controlled trials found Qigong significantly reduced anxiety, depression, and inflammatory biomarkers — effects comparable to aerobic exercise at lower intensity. Multiple systematic reviews confirm Tai Chi\'s superiority over conventional balance training for fall prevention in older adults. Acupuncture shows consistent efficacy for chronic pain, migraine prophylaxis, and chemotherapy-induced nausea across Cochrane-level reviews.',
      'The Five Elements framework — Wood, Fire, Earth, Metal, Water — maps organ systems, emotional states, seasons, and dietary tendencies onto a cyclical model of mutual generation and control. Liver (Wood) feeds Heart (Fire); Heart feeds Spleen (Earth); Spleen feeds Lung (Metal); Lung feeds Kidney (Water); Kidney feeds Liver. Disruption in any element propagates through the cycle. This is a systems map of physiological interdependence — mechanistically different from biomedical accounts, but structurally identical to the insight systems biology is re-deriving from first principles.',
      'For the HOLOS practitioner, Qi cultivation means attending to the flow of vital energy through consistent daily practice: morning Qigong, seasonal dietary adjustment, emotional regulation, and the cultivation of Shen — spirit and purposeful awareness. These practices maintain the conditions under which the organism heals itself. The goal is not an exotic state but a baseline of integrated self-regulation.',
    ]
  },
  'sleep-traditions': {
    author: 'Moshe Ostrovsky',
    body: [
      'Every major medical tradition developed a sophisticated theory of sleep, and when you compare them across cultures and centuries, the convergences are more remarkable than the differences. Without sleep trackers, EEG, or chronobiology, physicians across four continents arrived at near-identical conclusions about when to sleep, for how long, and under what conditions.',
      'Ayurveda prescribes sleeping during the Kapha time of night — approximately 10pm to 2am — when the earth-water element supports the deepest anabolic restoration. Rising before 6am during the Vata period aligns the waking state with mental clarity and lightness. Chronobiological research confirms that circadian alignment — sleeping when melatonin peaks, rising with early morning light — improves slow-wave sleep duration by 20–30% independent of total sleep hours.',
      'The Rambam was explicit: "Among the things that harm the body and shorten life: staying awake at night and shortening sleep." He prescribed sleeping on the right side first, then turning to the left — a recommendation modern gastrointestinal research partially confirms. Right-side sleeping reduces acid reflux; left-side sleeping enhances lymphatic drainage of the thoracic duct and may improve cardiac output.',
      'Tibetan medicine describes sleep as the time when Lung — the wind-humour governing mental activity — settles, and the subtle channels of the body undergo repair. This maps onto the glymphatic hypothesis confirmed in 2013 by Maiken Nedergaard: during deep sleep, cerebrospinal fluid flushes metabolic waste — including amyloid-beta — from the brain at 60% greater volume than during waking. Poor sleep quality is now the single most consistently modifiable risk factor for Alzheimer\'s disease.',
      'The cross-tradition consensus: sleep at consistent times aligned with natural light cycles; keep the sleep environment cool, dark, and quiet; avoid stimulation in the final hour before sleep; and treat sleep as active biological restoration rather than passive unconsciousness. The HOLOS Sleep dimension scores circadian alignment, sleep debt accumulation, subjective quality, and daytime functional consequences — providing a complete picture rather than a single metric.',
    ]
  },
  'stress-dimension': {
    author: 'Moshe Ostrovsky',
    body: [
      'Allostatic load is the cumulative physiological cost of chronic adaptation — what happens to the body when the stress response, designed for acute threats, is activated continuously over months and years. The term was introduced by Bruce McEwen in 1993, but the observation it names is ancient: every wisdom tradition identified sustained emotional disturbance as a primary driver of chronic disease.',
      'The primary mediators are cortisol, adrenaline, and pro-inflammatory cytokines. Brief cortisol surges sharpen cognition, mobilise energy, and suppress pain. Chronic cortisol elevation does the opposite: it suppresses hippocampal neurogenesis, impairing memory and learning; dysregulates glucose metabolism, driving insulin resistance; disrupts circadian rhythm, degrading sleep architecture; and accelerates cellular ageing via telomere shortening. This is why chronic psychological stress predicts cardiovascular disease, autoimmune disorders, metabolic syndrome, and depression — not as a risk factor alongside others but as an upstream driver of all of them.',
      'Most stress interventions fail because they address the subjective feeling of stress rather than the biological debt that accumulates beneath it. Breathing exercises and mindfulness reduce acute arousal. They do not clear the allostatic burden built up over months of chronic activation. Only a sustained reduction in allostatic inputs — improved sleep, reduced inflammation, manageable workload, relational safety, restored sense of meaning — combined with systematic recovery practices can do that.',
      'Ayurveda identifies stress-driven illness as Vata aggravation and prescribes grounding: warm, oily foods; slow rhythmic movement; regular daily routine; and adaptogenic herbs including ashwagandha, which a recent RCT found reduces serum cortisol by 27.9% after 60 days. Daoist Qigong and Tai Chi restore smooth Qi flow and settle the Shen. The Rambam prescribed rest, friendship, meaningful work, and moderation as the structural conditions for psychological health. Tibetan practice works directly with the avoidance and elaboration patterns that amplify stress into suffering.',
      'The HOLOS Stress dimension does not merely ask how stressed you feel. It assesses sleep quality, recovery speed, emotional regulation capacity, presence of meaning and social support, and — where self-reported data permits — estimates of inflammatory burden. Recommendations are drawn from whichever tradition\'s toolkit addresses the root drivers most directly, ranked by likely impact given your overall nine-dimension profile.',
    ]
  },
  'avicenna-canon': {
    author: 'Moshe Ostrovsky',
    body: [
      'Ibn Sina (980–1037) — known in the West as Avicenna — was the most influential physician in the history of medicine. His Canon of Medicine (Al-Qanun fi al-Tibb) was the standard medical textbook in European universities from the 12th to the 17th century, a tenure no other medical text has approached. It synthesised Greek, Persian, and Islamic medicine into a framework that outlasted every component tradition.',
      'The Canon identifies six categories of factors that determine health — the "six necessary things": air and environment; food and drink; bodily movement and rest; psychic movement and rest (emotional states); sleep and wakefulness; and retention and evacuation. These are not six separate prescriptions. They are six dimensions of a single integrated system, and disruption in any one propagates through the others — a systems-level insight that biomedicine is only now formalising.',
      'On air quality, Avicenna\'s observations were prescient: he described how stagnant air and confined spaces caused disease, recommended ventilation for hospitals, and designed quarantine procedures for infectious illness — a millennium before germ theory provided the mechanism. Modern environmental epidemiology consistently identifies air quality as among the strongest environmental determinants of chronic disease burden.',
      'On food, the Canon distinguishes foods by their effect on the body\'s temperament — their heating, cooling, moistening, or drying properties — and prescribes dietary adjustments to restore constitutional balance. The structural insight — that dietary prescription should be individualised to constitution and current health state, not universalised — is exactly what precision nutrition research is now rediscovering through nutritional genomics and microbiome science.',
      'On emotional states, Avicenna was direct: "Joy expands the vital spirit; grief constricts it; anger heats the blood; fear chills it." The Canon\'s prescriptions for psychological wellbeing — meaningful work, beautiful environments, close friendship, moderation of passion, and intellectual engagement — anticipate modern evidence-based interventions for chronic disease by nearly a thousand years. HOLOS uses the Avicenna framework as one of its eight lenses for interpreting assessment data and prioritising the interventions most likely to restore equilibrium.',
    ]
  },
  'tibetan-three-humours': {
    author: 'Moshe Ostrovsky',
    body: [
      'Tibetan medicine (Sowa Rigpa, "the knowledge of healing") is one of the world\'s oldest complete medical systems, developed over two millennia at the intersection of Indian Ayurveda, Chinese medicine, and the indigenous Bön healing tradition. Its foundational model identifies three humours — Lung, Tripa, and Beken — as the primary forces that determine health, and disease as the disruption of their dynamic balance.',
      'Lung (pronounced "loong") is the wind principle: it governs all movement, both physical — breath, nerve impulse, circulation — and mental — thought, intention, and emotion. Balanced Lung produces vitality, clarity, enthusiasm, and creative intelligence. Disturbed Lung manifests as anxiety, insomnia, trembling, dry skin, tinnitus, and a scattered, overwhelmed mental state — mapping closely onto what Western psychiatry describes as anxiety spectrum disorders and what Ayurveda calls Vata aggravation.',
      'Tripa — bile — is the fire principle: transformation, digestion of food and experience, sharp perception, and the capacity for discrimination and decision. Balanced Tripa produces intelligence, courage, and metabolic efficiency. Disturbed Tripa produces inflammation, skin disease, fever, irritability, perfectionism, and the chronic dissatisfaction of insatiability. This correlates with Ayurvedic Pitta imbalance and, in biomedical terms, with the chronic low-grade inflammatory state now recognised as a 